<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>lifequest-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gvn.GvnFramework.AspNetCore" />
    <PackageReference Include="Gvn.GvnFramework.Logging" />
    <PackageReference Include="Gvn.GvnFramework.Swagger" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LifeQuest.Infrastructure\LifeQuest.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LifeQuest.Api.IntegrationTests" />
  </ItemGroup>

</Project>
