// <auto-generated>
// tools/mobile/gen-icons.mjs tarafından web ikon setinden (ui/icon.ts) üretildi. Elle düzenlemeyin.
// </auto-generated>
namespace LifeQuest.Mobile.Core.Formatting;

/// <summary>24×24 çizgi ikonu: SVG yol verisi; <see cref="Rotated"/> ise 180° döndürülerek çizilir.</summary>
public sealed record IconShape(string Data, bool Rotated);

public static class Icons
{
    public static IReadOnlyDictionary<string, IconShape> All { get; } = new Dictionary<string, IconShape>
    {
        ["compass"] = new("M15.5 8.5 L13.2 13.2 L8.5 15.5 L10.8 10.8 z M3 12 a9 9 0 1 0 18 0 a9 9 0 1 0 -18 0 z", false),
        ["landmark"] = new("M3 21 h18 M4 10 h16 M12 3 L3.5 8 h17 z M6 10 v8 M10 10 v8 M14 10 v8 M18 10 v8", false),
        ["book"] = new("M5 4 h11 a3 3 0 0 1 3 3 v13 H8 a3 3 0 0 1 -3 -3 z M5 17 a3 3 0 0 1 3 -3 h11", false),
        ["users"] = new("M2.5 20 a6.5 6.5 0 0 1 13 0 M17 14.5 a5 5 0 0 1 4.5 5 M5.5 8 a3.5 3.5 0 1 0 7 0 a3.5 3.5 0 1 0 -7 0 z M14.5 9 a2.5 2.5 0 1 0 5 0 a2.5 2.5 0 1 0 -5 0 z", false),
        ["activity"] = new("M3 12 h4 l3 -8 l4 16 l3 -8 h4", false),
        ["palette"] = new("M12 3 a9 9 0 1 0 0 18 c1.1 0 2 -.8 2 -1.8 c0 -.5 -.2 -.9 -.5 -1.2 a1.7 1.7 0 0 1 1.3 -3 H17 a4 4 0 0 0 4 -4 c0 -4.4 -4 -8 -9 -8 z M6.5 11 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0 z M9 7 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0 z M13.5 7 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0 z", false),
        ["leaf"] = new("M5 19 c0 -8 5 -14 15 -15 c-1 10 -7 15 -15 15 z M5 19 l8 -8", false),
        ["sparkles"] = new("M12 3 l1.8 4.7 l4.7 1.8 l-4.7 1.8 L12 16 l-1.8 -4.7 l-4.7 -1.8 l4.7 -1.8 z M19 15 l.8 2.2 l2.2 .8 l-2.2 .8 L19 21 l-.8 -2.2 L16 18 l2.2 -.8 z", false),
        ["sun"] = new("M12 2 v2 M12 20 v2 M4.9 4.9 l1.4 1.4 M17.7 17.7 l1.4 1.4 M2 12 h2 M20 12 h2 M4.9 19.1 l1.4 -1.4 M17.7 6.3 l1.4 -1.4 M8 12 a4 4 0 1 0 8 0 a4 4 0 1 0 -8 0 z", false),
        ["cloud"] = new("M17.5 19 a4.5 4.5 0 0 0 .5 -8.97 A6 6 0 0 0 6.34 9.5 A4.75 4.75 0 0 0 6.75 19 z", false),
        ["cloud-rain"] = new("M16 13.5 a4 4 0 0 0 .4 -7.97 A5.5 5.5 0 0 0 5.8 7.2 A4.2 4.2 0 0 0 6.2 15.5 M8 17 l-1 3 M12 17 l-1 3 M16 17 l-1 3", false),
        ["calendar"] = new("M3 9 h18 M8 3 v4 M16 3 v4 M5 5 h14 a2 2 0 0 1 2 2 v12 a2 2 0 0 1 -2 2 H5 a2 2 0 0 1 -2 -2 V7 a2 2 0 0 1 2 -2 z", false),
        ["moon"] = new("M20 14.5 A8 8 0 1 1 9.5 4 a6.5 6.5 0 0 0 10.5 10.5 z", false),
        ["monitor"] = new("M8 20 h8 M12 16 v4 M5 4 h14 a2 2 0 0 1 2 2 v8 a2 2 0 0 1 -2 2 h-14 a2 2 0 0 1 -2 -2 v-8 a2 2 0 0 1 2 -2 z", false),
        ["check"] = new("M5 12.5 l5 5 L19 7", false),
        ["x"] = new("M6 6 l12 12 M18 6 L6 18", false),
        ["clock"] = new("M12 7 v5 l3 2 M3 12 a9 9 0 1 0 18 0 a9 9 0 1 0 -18 0 z", false),
        ["coins"] = new("M14.5 9 h-4 a1.5 1.5 0 0 0 0 3 h3 a1.5 1.5 0 0 1 0 3 h-4 M12 7.5 V9 M12 15 v1.5 M3 12 a9 9 0 1 0 18 0 a9 9 0 1 0 -18 0 z", false),
        ["star"] = new("M12 3 l2.7 5.6 l6.1 .9 l-4.4 4.3 l1 6.1 L12 17 l-5.4 2.9 l1 -6.1 l-4.4 -4.3 l6.1 -.9 z", false),
        ["zap"] = new("M13 2 L4 14 h7 l-1 8 l9 -12 h-7 z", false),
        ["arrow-left"] = new("M19 12 H5 M11 6 l-6 6 l6 6", false),
        ["chevron-right"] = new("M9 6 l6 6 l-6 6", false),
        ["trophy"] = new("M8 4 h8 v5 a4 4 0 0 1 -8 0 z M8 6 H5 a3 3 0 0 0 3 5 M16 6 h3 a3 3 0 0 1 -3 5 M12 13 v4 M8 21 h8 M9.5 17 h5 l.5 4 h-6 z", false),
        ["list"] = new("M10 6 h10 M10 12 h10 M10 18 h10 M3.5 6 l1.5 1.5 L7.5 5 M3.5 12 l1.5 1.5 l2.5 -2.5 M3.5 18 l1.5 1.5 l2.5 -2.5", false),
        ["user"] = new("M4 21 a8 8 0 0 1 16 0 M8 8 a4 4 0 1 0 8 0 a4 4 0 1 0 -8 0 z", false),
        ["lock"] = new("M8 11 V8 a4 4 0 0 1 8 0 v3 M7 11 h10 a2 2 0 0 1 2 2 v6 a2 2 0 0 1 -2 2 h-10 a2 2 0 0 1 -2 -2 v-6 a2 2 0 0 1 2 -2 z", false),
        ["logout"] = new("M15 4 h3 a2 2 0 0 1 2 2 v12 a2 2 0 0 1 -2 2 h-3 M10 8 l-4 4 l4 4 M6 12 h10", false),
        ["trash"] = new("M4 7 h16 M9 7 V4 h6 v3 M6 7 l1 13 h10 l1 -13 M10 11 v6 M14 11 v6", false),
        ["map-pin"] = new("M12 21 s7 -6.2 7 -12 a7 7 0 0 0 -14 0 c0 5.8 7 12 7 12 z M9.5 9 a2.5 2.5 0 1 0 5 0 a2.5 2.5 0 1 0 -5 0 z", false),
        ["thumbs-up"] = new("M7 11 v9 H4 v-9 z M7 11 l4 -7.5 a2 2 0 0 1 3.2 2.1 L13 10.5 h5.6 a2 2 0 0 1 2 2.4 l-1.3 5.6 a2 2 0 0 1 -2 1.5 H7", false),
        ["thumbs-down"] = new("M7 11 v9 H4 v-9 z M7 11 l4 -7.5 a2 2 0 0 1 3.2 2.1 L13 10.5 h5.6 a2 2 0 0 1 2 2.4 l-1.3 5.6 a2 2 0 0 1 -2 1.5 H7", true),
        ["refresh"] = new("M20 11 a8 8 0 0 0 -14.5 -4.5 L4 8 M4 4 v4 h4 M4 13 a8 8 0 0 0 14.5 4.5 L20 16 M20 20 v-4 h-4", false),
        ["plus"] = new("M12 5 v14 M5 12 h14", false),
        ["info"] = new("M12 11 v5 M12 8 h.01 M3 12 a9 9 0 1 0 18 0 a9 9 0 1 0 -18 0 z", false),
        ["flag"] = new("M5 21 V4 M5 4 h11 l-2 4 l2 4 H5", false),
        ["heart"] = new("M12 20 s-7 -4.4 -7 -10 a4 4 0 0 1 7 -2.6 A4 4 0 0 1 19 10 c0 5.6 -7 10 -7 10 z", false),
        ["target"] = new("M3 12 a9 9 0 1 0 18 0 a9 9 0 1 0 -18 0 z M7 12 a5 5 0 1 0 10 0 a5 5 0 1 0 -10 0 z M11 12 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0 z", false),
        ["hourglass"] = new("M7 3 h10 M7 21 h10 M8 3 v3 l4 5 l4 -5 V3 M8 21 v-3 l4 -5 l4 5 v3", false),
    };

    public static IconShape Get(string? name) => name is not null && All.TryGetValue(name, out var shape) ? shape : All["info"];
}
