<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Gvn.GvnFramework.EntityFrameworkCore" />
    <PackageReference Include="Gvn.GvnFramework.Caching" />
    <PackageReference Include="Gvn.GvnFramework.BackgroundJobs" />
    <PackageReference Include="Gvn.GvnFramework.Modularity" />
    <PackageReference Include="Gvn.GvnFramework.DependencyInjection" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Lib.Net.Http.WebPush" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LifeQuest.Application\LifeQuest.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LifeQuest.Catalog.Tests" />
    <InternalsVisibleTo Include="LifeQuest.Simulation" />
    <InternalsVisibleTo Include="LifeQuest.Api.IntegrationTests" />
  </ItemGroup>

</Project>
