// <auto-generated />
using System;
using System.Collections.Generic;
using LifeQuest.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LifeQuest.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LifeQuestDbContext))]
    partial class LifeQuestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LifeQuest.Domain.Admin.AdminAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("actor_email");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetLabel")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("target_label");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit_entries");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_admin_audit_entries_created_at");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_admin_audit_entries_action_created_at");

                    b.ToTable("admin_audit_entries", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Catalog.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_interests");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_interests_code");

                    b.ToTable("interests", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Catalog.InterestRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<Guid>("FromInterestId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_interest_id");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relation_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<Guid>("ToInterestId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_interest_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_interest_relations");

                    b.HasIndex("ToInterestId")
                        .HasDatabaseName("ix_interest_relations_to_interest_id");

                    b.HasIndex("FromInterestId", "ToInterestId")
                        .IsUnique()
                        .HasDatabaseName("ix_interest_relations_from_interest_id_to_interest_id");

                    b.ToTable("interest_relations", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Catalog.QuestTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int>("CooldownDays")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_days");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DayParts")
                        .HasColumnType("integer")
                        .HasColumnName("day_parts");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Effort")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Light")
                        .HasColumnName("effort");

                    b.PrimitiveCollection<List<Guid>>("InterestIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("interest_ids");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsOutdoor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_outdoor");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean")
                        .HasColumnName("is_starter");

                    b.Property<int>("MaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_minutes");

                    b.Property<int>("MinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("min_minutes");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_age");

                    b.Property<bool>("RequiresCity")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_city");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision")
                        .HasColumnName("risk_score");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("safety");

                    b.Property<string>("SecondaryCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("secondary_category");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Seed")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_quest_templates");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_quest_templates_code");

                    b.HasIndex("IsActive", "Safety")
                        .HasDatabaseName("ix_quest_templates_is_active_safety");

                    b.ToTable("quest_templates", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Community.QuestIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("Flags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("flags");

                    b.Property<bool>("IsOutdoor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_outdoor");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("reviewed_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_quest_ideas");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_quest_ideas_status_submitted_at");

                    b.HasIndex("UserId", "SubmittedAt")
                        .HasDatabaseName("ix_quest_ideas_user_id_submitted_at");

                    b.ToTable("quest_ideas", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Experiments.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("Hypothesis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hypothesis");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TreatmentOverrides")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("treatment_overrides");

                    b.Property<double>("TreatmentShare")
                        .HasColumnType("double precision")
                        .HasColumnName("treatment_share");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_experiments");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("ux_experiments_single_running")
                        .HasFilter("status = 'Running'");

                    b.ToTable("experiments", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_count");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockoutEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_ends_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_until");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_email");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Notifications.WeeklySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("message");

                    b.PrimitiveCollection<int[]>("NewCategories")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("new_categories");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("title");

                    b.Property<string>("TopCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("top_category");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer")
                        .HasColumnName("xp_earned");

                    b.HasKey("Id")
                        .HasName("pk_weekly_summaries");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_summaries_user_id_week_start");

                    b.ToTable("weekly_summaries", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Profiles.UserInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InterestId")
                        .HasColumnType("uuid")
                        .HasColumnName("interest_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_user_interests");

                    b.HasIndex("InterestId")
                        .HasDatabaseName("ix_user_interests_interest_id");

                    b.HasIndex("UserProfileId", "InterestId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_interests_user_profile_id_interest_id");

                    b.ToTable("user_interests", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Profiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Budget")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("budget");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DiscoveryRadius")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("discovery_radius");

                    b.PrimitiveCollection<int[]>("Goals")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("goals");

                    b.Property<string>("MaxPhysicalEffort")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Vigorous")
                        .HasColumnName("max_physical_effort");

                    b.Property<string>("NotificationPreference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("WeeklySummary")
                        .HasColumnName("notification_preference");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WeeklyAvailableMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("weekly_available_minutes");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_user_id");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.CategoryProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_count");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("PlayerProgressId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_progress_id");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_category_progress");

                    b.HasIndex("PlayerProgressId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_category_progress_player_progress_id_category");

                    b.ToTable("category_progress", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.PlayerProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_count");

                    b.Property<int>("LifeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("life_level");

                    b.Property<int>("LifeXp")
                        .HasColumnType("integer")
                        .HasColumnName("life_xp");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("TotalCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("total_completed");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_player_progress");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_progress_user_id");

                    b.ToTable("player_progress", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.UnlockedAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("PlayerProgressId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_progress_id");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.HasKey("Id")
                        .HasName("pk_user_achievements");

                    b.HasIndex("PlayerProgressId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_user_achievements_player_progress_id_code");

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.XpTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.Property<int>("LifeXp")
                        .HasColumnType("integer")
                        .HasColumnName("life_xp");

                    b.Property<string>("PrimaryCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("primary_category");

                    b.Property<int>("PrimaryCategoryXp")
                        .HasColumnType("integer")
                        .HasColumnName("primary_category_xp");

                    b.Property<string>("SecondaryCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("secondary_category");

                    b.Property<int>("SecondaryCategoryXp")
                        .HasColumnType("integer")
                        .HasColumnName("secondary_category_xp");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_xp_transactions");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_xp_transactions_source_type_source_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_xp_transactions_user_id_created_at");

                    b.ToTable("xp_transactions", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Quests.SavedQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_quests");

                    b.HasIndex("UserId", "TemplateId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_quests_user_id_template_id");

                    b.ToTable("saved_quests", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Quests.UserQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Cost")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Effort")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Light")
                        .HasColumnName("effort");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_id");

                    b.Property<string>("ExperimentVariant")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("experiment_variant");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("explanation");

                    b.Property<DateTime?>("FeedbackAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_at");

                    b.PrimitiveCollection<List<Guid>>("InterestIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("interest_ids");

                    b.Property<bool>("IsExploration")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exploration");

                    b.Property<int>("MaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_minutes");

                    b.Property<int>("MinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("min_minutes");

                    b.Property<string>("NarrationSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Template")
                        .HasColumnName("narration_source");

                    b.Property<DateOnly>("OfferDate")
                        .HasColumnType("date")
                        .HasColumnName("offer_date");

                    b.Property<DateTime>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<DateTime?>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("Preference")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("preference");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.PrimitiveCollection<List<string>>("ReasonCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reason_codes");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SecondaryCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("secondary_category");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("skip_reason");

                    b.Property<DateTime?>("SkippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("skipped_at");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("template_code");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("template_version");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("Reward", "LifeQuest.Domain.Quests.UserQuest.Reward#QuestReward", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("LifeXp")
                                .HasColumnType("integer")
                                .HasColumnName("reward_life_xp");

                            b1.Property<decimal>("NoveltyMultiplier")
                                .HasPrecision(4, 2)
                                .HasColumnType("numeric(4,2)")
                                .HasColumnName("reward_novelty_multiplier");

                            b1.Property<int>("PrimaryCategoryXp")
                                .HasColumnType("integer")
                                .HasColumnName("reward_primary_category_xp");

                            b1.Property<int>("SecondaryCategoryXp")
                                .HasColumnType("integer")
                                .HasColumnName("reward_secondary_category_xp");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Score", "LifeQuest.Domain.Quests.UserQuest.Score#ScoreBreakdown", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Context")
                                .HasColumnType("double precision")
                                .HasColumnName("score_context");

                            b1.Property<double>("Diversity")
                                .HasColumnType("double precision")
                                .HasColumnName("score_diversity");

                            b1.Property<double>("FeedbackFit")
                                .HasColumnType("double precision")
                                .HasColumnName("score_feedback_fit");

                            b1.Property<double>("Friction")
                                .HasColumnType("double precision")
                                .HasColumnName("score_friction");

                            b1.Property<double>("GoalFit")
                                .HasColumnType("double precision")
                                .HasColumnName("score_goal_fit");

                            b1.Property<double>("Interest")
                                .HasColumnType("double precision")
                                .HasColumnName("score_interest");

                            b1.Property<double>("Novelty")
                                .HasColumnType("double precision")
                                .HasColumnName("score_novelty");

                            b1.Property<double>("Repetition")
                                .HasColumnType("double precision")
                                .HasColumnName("score_repetition");

                            b1.Property<double>("Risk")
                                .HasColumnType("double precision")
                                .HasColumnName("score_risk");

                            b1.Property<double>("Total")
                                .HasColumnType("double precision")
                                .HasColumnName("score_total");
                        });

                    b.HasKey("Id")
                        .HasName("pk_user_quests");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_user_quests_template_id");

                    b.HasIndex("ExperimentId", "ExperimentVariant")
                        .HasDatabaseName("ix_user_quests_experiment_id_experiment_variant");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_user_quests_status_expires_at");

                    b.HasIndex("UserId", "OfferDate", "Slot")
                        .IsUnique()
                        .HasDatabaseName("ux_user_quests_daily_slot")
                        .HasFilter("source = 'Daily'");

                    b.HasIndex("UserId", "OfferDate", "Source")
                        .HasDatabaseName("ix_user_quests_user_id_offer_date_source");

                    b.HasIndex("UserId", "Status", "ExpiresAt")
                        .HasDatabaseName("ix_user_quests_user_id_status_expires_at");

                    b.ToTable("user_quests", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Recommendations.RecommendationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Overrides")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("overrides");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_settings");

                    b.ToTable("recommendation_settings", (string)null);
                });

            modelBuilder.Entity("LifeQuest.Domain.Catalog.InterestRelation", b =>
                {
                    b.HasOne("LifeQuest.Domain.Catalog.Interest", null)
                        .WithMany()
                        .HasForeignKey("FromInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interest_relations_interests_from_interest_id");

                    b.HasOne("LifeQuest.Domain.Catalog.Interest", null)
                        .WithMany()
                        .HasForeignKey("ToInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interest_relations_interests_to_interest_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Community.QuestIdea", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_ideas_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Notifications.WeeklySummary", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_summaries_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Profiles.UserInterest", b =>
                {
                    b.HasOne("LifeQuest.Domain.Catalog.Interest", null)
                        .WithMany()
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_interests_interest_id");

                    b.HasOne("LifeQuest.Domain.Profiles.UserProfile", null)
                        .WithMany("Interests")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_user_profiles_user_profile_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Profiles.UserProfile", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.CategoryProgress", b =>
                {
                    b.HasOne("LifeQuest.Domain.Progression.PlayerProgress", null)
                        .WithMany("Categories")
                        .HasForeignKey("PlayerProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_progress_player_progress_player_progress_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.PlayerProgress", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_progress_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.UnlockedAchievement", b =>
                {
                    b.HasOne("LifeQuest.Domain.Progression.PlayerProgress", null)
                        .WithMany("Achievements")
                        .HasForeignKey("PlayerProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_player_progress_player_progress_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.XpTransaction", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_xp_transactions_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Quests.SavedQuest", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_quests_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Quests.UserQuest", b =>
                {
                    b.HasOne("LifeQuest.Domain.Identity.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_quests_user_accounts_user_id");
                });

            modelBuilder.Entity("LifeQuest.Domain.Profiles.UserProfile", b =>
                {
                    b.Navigation("Interests");
                });

            modelBuilder.Entity("LifeQuest.Domain.Progression.PlayerProgress", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
