// <auto-generated>
// tools/mobile/gen-strings.mjs tarafından web sözlüğünden (core/i18n/sections) üretildi. Elle düzenlemeyin;
// metni web'de değiştirip script'i yeniden çalıştırın.
// </auto-generated>
#nullable enable
namespace LifeQuest.Mobile.Core.Localization;

/// <summary>Uygulamanın tüm kullanıcı metinleri; her okuma o anki dili döndürür.</summary>
public sealed class Strings
{
    public CommonStrings Common { get; } = new();
    public NavStrings Nav { get; } = new();
    public TitlesStrings Titles { get; } = new();
    public ErrorsStrings Errors { get; } = new();
    public FormatStrings Format { get; } = new();
    public LabelsStrings Labels { get; } = new();
    public UiStrings Ui { get; } = new();
    public AuthStrings Auth { get; } = new();
    public OnboardingStrings Onboarding { get; } = new();
    public TodayStrings Today { get; } = new();
    public SuggestStrings Suggest { get; } = new();
    public QuestsStrings Quests { get; } = new();
    public QuestStrings Quest { get; } = new();
    public CelebrationStrings Celebration { get; } = new();
    public PartyStrings Party { get; } = new();
    public SavedStrings Saved { get; } = new();
    public ProgressStrings Progress { get; } = new();
    public IdeasStrings Ideas { get; } = new();
    public ProfileStrings Profile { get; } = new();
    public ReminderStrings Reminder { get; } = new();
}

public interface ILabelsCostItem
{
    string Short { get; }
    string Label { get; }
    string Hint { get; }
}

public interface ILabelsRadiusItem
{
    string Label { get; }
    string Description { get; }
}

public interface ILabelsSkipReasonsItem
{
    string Label { get; }
    string Hint { get; }
}

public interface ILabelsWeeklyTimeItem
{
    string Label { get; }
    string Short { get; }
    string Hint { get; }
}

public interface ILabelsEffortItem
{
    string Label { get; }
    string Hint { get; }
}

public interface ILabelsEffortLimitItem
{
    string Label { get; }
    string Hint { get; }
}

public sealed class CommonLanguagesStrings : LocalizedStrings
{
    public string Tr => T("Türkçe", "Türkçe");
    public string En => T("English", "English");

    public string this[string key] => key switch
    {
        "tr" => Tr,
        "en" => En,
        _ => key,
    };
}

public sealed class CommonStrings : LocalizedStrings
{
    public string AppName => T("LifeQuest", "LifeQuest");
    public string Back => T("Geri", "Back");
    public string Close => T("Kapat", "Close");
    public string Cancel => T("Vazgeç", "Cancel");
    public string Save => T("Kaydet", "Save");
    public string Saved => T("Kaydedildi.", "Saved.");
    public string Delete => T("Sil", "Delete");
    public string Edit => T("Düzenle", "Edit");
    public string Remove => T("Kaldır", "Remove");
    public string Retry => T("Tekrar dene", "Try again");
    public string Loading => T("Yükleniyor…", "Loading…");
    public string You => T("sen", "you");
    public string Language => T("Dil", "Language");
    public CommonLanguagesStrings Languages { get; } = new();
    public string Xp => T("XP", "XP");
    public string MinutesShort => T("dk", "min");
}

public sealed class NavStrings : LocalizedStrings
{
    public string Today => T("Bugün", "Today");
    public string Quests => T("Görevlerim", "My quests");
    public string Progress => T("İlerleme", "Progress");
    public string Profile => T("Profil", "Profile");
    public string MainMenu => T("Ana menü", "Main menu");

    public string this[string key] => key switch
    {
        "today" => Today,
        "quests" => Quests,
        "progress" => Progress,
        "profile" => Profile,
        "mainMenu" => MainMenu,
        _ => key,
    };
}

public sealed class TitlesStrings : LocalizedStrings
{
    public string Login => T("Giriş", "Sign in");
    public string Register => T("Kayıt ol", "Sign up");
    public string Onboarding => T("Hoş geldin", "Welcome");
    public string Today => T("Bugün", "Today");
    public string Party => T("Quest Party", "Quest Party");
    public string Saved => T("Sonra yaparım", "Later");
    public string Ideas => T("Bir deneyim öner", "Suggest an experience");
    public string Suggest => T("Boş vaktim var", "I have free time");
    public string Quest => T("Quest", "Quest");
    public string Quests => T("Görevlerim", "My quests");
    public string Progress => T("İlerleme", "Progress");
    public string Profile => T("Profil", "Profile");
    public string AdminMetrics => T("Ürün metrikleri", "Product metrics");
    public string AdminUsers => T("Kullanıcılar", "Users");
    public string AdminCatalog => T("Katalog", "Catalog");
    public string AdminNewTemplate => T("Yeni template", "New template");
    public string AdminTemplate => T("Template", "Template");
    public string AdminIdeas => T("Topluluk fikirleri", "Community ideas");
    public string AdminExperiments => T("Deneyler", "Experiments");
    public string AdminExperiment => T("Deney", "Experiment");
    public string AdminPlaces => T("Mekânlar ve etkinlikler", "Places and events");
    public string AdminWeights => T("Öneri ayarları", "Recommendation settings");
    public string AdminAudit => T("Denetim kaydı", "Audit log");
    public string AdminSuffix => T("Yönetim", "Admin");

    public string this[string key] => key switch
    {
        "login" => Login,
        "register" => Register,
        "onboarding" => Onboarding,
        "today" => Today,
        "party" => Party,
        "saved" => Saved,
        "ideas" => Ideas,
        "suggest" => Suggest,
        "quest" => Quest,
        "quests" => Quests,
        "progress" => Progress,
        "profile" => Profile,
        "adminMetrics" => AdminMetrics,
        "adminUsers" => AdminUsers,
        "adminCatalog" => AdminCatalog,
        "adminNewTemplate" => AdminNewTemplate,
        "adminTemplate" => AdminTemplate,
        "adminIdeas" => AdminIdeas,
        "adminExperiments" => AdminExperiments,
        "adminExperiment" => AdminExperiment,
        "adminPlaces" => AdminPlaces,
        "adminWeights" => AdminWeights,
        "adminAudit" => AdminAudit,
        "adminSuffix" => AdminSuffix,
        _ => key,
    };
}

public sealed class ErrorsStrings : LocalizedStrings
{
    public string Unknown => T("Beklenmeyen bir hata oluştu.", "Something unexpected went wrong.");
    public string Network => T("Sunucuya ulaşılamıyor. Bağlantını kontrol et.", "Can't reach the server. Check your connection.");
    public string RateLimited => T("Çok fazla istek gönderildi. Biraz sonra tekrar dene.", "Too many requests. Please try again in a moment.");
    public string Server => T("Sunucuda bir sorun oluştu. Lütfen tekrar dene.", "Something went wrong on the server. Please try again.");
    public string Request => T("İstek tamamlanamadı.", "The request couldn't be completed.");
    public string Suspended => T("Hesabın askıya alındı. Destek ekibiyle iletişime geçebilirsin.", "Your account has been suspended. You can contact the support team.");
    public string SessionExpired => T("Oturumun sona erdi. Lütfen tekrar giriş yap.", "Your session has ended. Please sign in again.");

    public string this[string key] => key switch
    {
        "unknown" => Unknown,
        "network" => Network,
        "rateLimited" => RateLimited,
        "server" => Server,
        "request" => Request,
        "suspended" => Suspended,
        "sessionExpired" => SessionExpired,
        _ => key,
    };
}

public sealed class FormatGreetingsStrings : LocalizedStrings
{
    public string Night => T("İyi geceler", "Good night");
    public string Morning => T("Günaydın", "Good morning");
    public string Day => T("İyi günler", "Good afternoon");
    public string Evening => T("İyi akşamlar", "Good evening");

    public string this[string key] => key switch
    {
        "night" => Night,
        "morning" => Morning,
        "day" => Day,
        "evening" => Evening,
        _ => key,
    };
}

public sealed class FormatStrings : LocalizedStrings
{
    public string Min => T("dk", "min");
    public string Hour => T("sa", "h");
    public string Expired => T("Süresi doldu", "Expired");
    public string MinutesLeft(int n) => T($"{n} dakika kaldı", $"{n} {(n == 1 ? "minute" : "minutes")} left");
    public string HoursLeft(int n) => T($"{n} saat kaldı", $"{n} {(n == 1 ? "hour" : "hours")} left");
    public string DaysLeft(int n) => T($"{n} gün kaldı", $"{n} {(n == 1 ? "day" : "days")} left");
    public FormatGreetingsStrings Greetings { get; } = new();
    public string Percent(int n) => T($"%{n}", $"{n}%");
}

public sealed class LabelsCategoriesStrings : LocalizedStrings
{
    public string Explorer => T("Keşif", "Exploration");
    public string Culture => T("Kültür", "Culture");
    public string Learning => T("Öğrenme", "Learning");
    public string Social => T("Sosyal", "Social");
    public string Fitness => T("Hareket", "Movement");
    public string Creativity => T("Yaratıcılık", "Creativity");

    public string this[string key] => key switch
    {
        "Explorer" => Explorer,
        "Culture" => Culture,
        "Learning" => Learning,
        "Social" => Social,
        "Fitness" => Fitness,
        "Creativity" => Creativity,
        _ => key,
    };
}

public sealed class LabelsCategoryDescriptionsStrings : LocalizedStrings
{
    public string Explorer => T("Yeni mekânlar, semtler, lezzetler", "New places, neighborhoods, flavors");
    public string Culture => T("Sanat, sinema, müze, müzik", "Art, film, museums, music");
    public string Learning => T("Okuma, dil, bilim, yeni beceriler", "Reading, languages, science, new skills");
    public string Social => T("Arkadaşlar, topluluklar, gönüllülük", "Friends, communities, volunteering");
    public string Fitness => T("Yürüyüş, koşu, yoga, hareket", "Walking, running, yoga, movement");
    public string Creativity => T("Fotoğraf, çizim, yazı, el işi", "Photography, drawing, writing, crafts");

    public string this[string key] => key switch
    {
        "Explorer" => Explorer,
        "Culture" => Culture,
        "Learning" => Learning,
        "Social" => Social,
        "Fitness" => Fitness,
        "Creativity" => Creativity,
        _ => key,
    };
}

public sealed class LabelsCostFreeStrings : LocalizedStrings, ILabelsCostItem
{
    public string Short => T("Ücretsiz", "Free");
    public string Label => T("Ücretsiz", "Free");
    public string Hint => T("Para harcamadan", "No money needed");

    public string this[string key] => key switch
    {
        "short" => Short,
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsCostLowStrings : LocalizedStrings, ILabelsCostItem
{
    public string Short => T("₺", "$");
    public string Label => T("Düşük", "Low");
    public string Hint => T("Bir kahve parası", "The price of a coffee");

    public string this[string key] => key switch
    {
        "short" => Short,
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsCostMediumStrings : LocalizedStrings, ILabelsCostItem
{
    public string Short => T("₺₺", "$$");
    public string Label => T("Orta", "Medium");
    public string Hint => T("Bilet, ders ücreti", "A ticket or class fee");

    public string this[string key] => key switch
    {
        "short" => Short,
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsCostHighStrings : LocalizedStrings, ILabelsCostItem
{
    public string Short => T("₺₺₺", "$$$");
    public string Label => T("Yüksek", "High");
    public string Hint => T("Özel deneyimler", "Special experiences");

    public string this[string key] => key switch
    {
        "short" => Short,
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsCostStrings : LocalizedStrings
{
    public LabelsCostFreeStrings Free { get; } = new();
    public LabelsCostLowStrings Low { get; } = new();
    public LabelsCostMediumStrings Medium { get; } = new();
    public LabelsCostHighStrings High { get; } = new();

    public ILabelsCostItem this[string key] => key switch
    {
        "Free" => Free,
        "Low" => Low,
        "Medium" => Medium,
        "High" => High,
        _ => throw new KeyNotFoundException(key),
    };
}

public sealed class LabelsRadiusChillStrings : LocalizedStrings, ILabelsRadiusItem
{
    public string Label => T("Sakin", "Chill");
    public string Description => T("Çoğunlukla sevdiğin, tanıdık şeyler", "Mostly familiar things you like");

    public string this[string key] => key switch
    {
        "label" => Label,
        "description" => Description,
        _ => key,
    };
}

public sealed class LabelsRadiusExploreStrings : LocalizedStrings, ILabelsRadiusItem
{
    public string Label => T("Dengeli", "Balanced");
    public string Description => T("Tanıdık ile yeniyi dengeler", "Balances the familiar and the new");

    public string this[string key] => key switch
    {
        "label" => Label,
        "description" => Description,
        _ => key,
    };
}

public sealed class LabelsRadiusSurpriseMeStrings : LocalizedStrings, ILabelsRadiusItem
{
    public string Label => T("Şaşırt Beni", "Surprise Me");
    public string Description => T("Daha fazla yenilik ve sürpriz", "More novelty and surprises");

    public string this[string key] => key switch
    {
        "label" => Label,
        "description" => Description,
        _ => key,
    };
}

public sealed class LabelsRadiusStrings : LocalizedStrings
{
    public LabelsRadiusChillStrings Chill { get; } = new();
    public LabelsRadiusExploreStrings Explore { get; } = new();
    public LabelsRadiusSurpriseMeStrings SurpriseMe { get; } = new();

    public ILabelsRadiusItem this[string key] => key switch
    {
        "Chill" => Chill,
        "Explore" => Explore,
        "SurpriseMe" => SurpriseMe,
        _ => throw new KeyNotFoundException(key),
    };
}

public sealed class LabelsQuestTypesStrings : LocalizedStrings
{
    public string Daily => T("Günlük", "Daily");
    public string Weekly => T("Haftalık", "Weekly");
    public string Adventure => T("Macera", "Adventure");
    public string Epic => T("Destansı", "Epic");

    public string this[string key] => key switch
    {
        "Daily" => Daily,
        "Weekly" => Weekly,
        "Adventure" => Adventure,
        "Epic" => Epic,
        _ => key,
    };
}

public sealed class LabelsDifficultiesStrings : LocalizedStrings
{
    public string Easy => T("Kolay", "Easy");
    public string Medium => T("Orta", "Medium");
    public string Hard => T("Zor", "Hard");
    public string Heroic => T("Kahramanca", "Heroic");

    public string this[string key] => key switch
    {
        "Easy" => Easy,
        "Medium" => Medium,
        "Hard" => Hard,
        "Heroic" => Heroic,
        _ => key,
    };
}

public sealed class LabelsStatusesStrings : LocalizedStrings
{
    public string Offered => T("Önerildi", "Suggested");
    public string Accepted => T("Devam ediyor", "In progress");
    public string Completed => T("Tamamlandı", "Completed");
    public string Skipped => T("Geçildi", "Skipped");
    public string Expired => T("Süresi doldu", "Expired");

    public string this[string key] => key switch
    {
        "Offered" => Offered,
        "Accepted" => Accepted,
        "Completed" => Completed,
        "Skipped" => Skipped,
        "Expired" => Expired,
        _ => key,
    };
}

public sealed class LabelsSkipReasonsNotInterestedStrings : LocalizedStrings, ILabelsSkipReasonsItem
{
    public string Label => T("İlgimi çekmedi", "Not for me");
    public string Hint => T("Benzerlerini daha az göreceksin", "You'll see fewer like this");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsSkipReasonsTooExpensiveStrings : LocalizedStrings, ILabelsSkipReasonsItem
{
    public string Label => T("Pahalı", "Too expensive");
    public string Hint => T("Bütçene daha uygun öneriler gelir", "You'll get suggestions that fit your budget");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsSkipReasonsNoTimeStrings : LocalizedStrings, ILabelsSkipReasonsItem
{
    public string Label => T("Zamanım yok", "No time");
    public string Hint => T("Daha kısa görevler öne çıkar", "Shorter quests come first");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsSkipReasonsTooFarStrings : LocalizedStrings, ILabelsSkipReasonsItem
{
    public string Label => T("Uzak", "Too far");
    public string Hint => T("", "");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsSkipReasonsNotTodayStrings : LocalizedStrings, ILabelsSkipReasonsItem
{
    public string Label => T("Bugün uygun değil", "Not today");
    public string Hint => T("İlgi alanlarını etkilemez", "Doesn't affect your interests");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsSkipReasonsOtherStrings : LocalizedStrings, ILabelsSkipReasonsItem
{
    public string Label => T("Başka bir sebep", "Another reason");
    public string Hint => T("", "");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsSkipReasonsStrings : LocalizedStrings
{
    public LabelsSkipReasonsNotInterestedStrings NotInterested { get; } = new();
    public LabelsSkipReasonsTooExpensiveStrings TooExpensive { get; } = new();
    public LabelsSkipReasonsNoTimeStrings NoTime { get; } = new();
    public LabelsSkipReasonsTooFarStrings TooFar { get; } = new();
    public LabelsSkipReasonsNotTodayStrings NotToday { get; } = new();
    public LabelsSkipReasonsOtherStrings Other { get; } = new();

    public ILabelsSkipReasonsItem this[string key] => key switch
    {
        "NotInterested" => NotInterested,
        "TooExpensive" => TooExpensive,
        "NoTime" => NoTime,
        "TooFar" => TooFar,
        "NotToday" => NotToday,
        "Other" => Other,
        _ => throw new KeyNotFoundException(key),
    };
}

public sealed class LabelsScoreComponentsStrings : LocalizedStrings
{
    public string Interest => T("İlgi uyumu", "Interest match");
    public string Novelty => T("Yenilik", "Novelty");
    public string Context => T("Bağlam (saat, süre)", "Context (time, duration)");
    public string GoalFit => T("Hedeflerine uyum", "Fit with your goals");
    public string Diversity => T("Çeşitlilik", "Variety");
    public string FeedbackFit => T("Geri bildirimlerin", "Your feedback");
    public string Repetition => T("Tekrar", "Repetition");
    public string Friction => T("Engel (bütçe, süre)", "Friction (budget, time)");
    public string Risk => T("Risk", "Risk");

    public string this[string key] => key switch
    {
        "interest" => Interest,
        "novelty" => Novelty,
        "context" => Context,
        "goalFit" => GoalFit,
        "diversity" => Diversity,
        "feedbackFit" => FeedbackFit,
        "repetition" => Repetition,
        "friction" => Friction,
        "risk" => Risk,
        _ => key,
    };
}

public sealed class LabelsWeeklyTimeM120Strings : LocalizedStrings, ILabelsWeeklyTimeItem
{
    public string Label => T("1–2 saat", "1–2 hours");
    public string Short => T("1–2 sa", "1–2 h");
    public string Hint => T("Küçük molalar", "Short breaks");

    public string this[string key] => key switch
    {
        "label" => Label,
        "short" => Short,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsWeeklyTimeM300Strings : LocalizedStrings, ILabelsWeeklyTimeItem
{
    public string Label => T("3–5 saat", "3–5 hours");
    public string Short => T("3–5 sa", "3–5 h");
    public string Hint => T("Birkaç akşam", "A few evenings");

    public string this[string key] => key switch
    {
        "label" => Label,
        "short" => Short,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsWeeklyTimeM600Strings : LocalizedStrings, ILabelsWeeklyTimeItem
{
    public string Label => T("6–10 saat", "6–10 hours");
    public string Short => T("6–10 sa", "6–10 h");
    public string Hint => T("Hafta sonları dahil", "Including weekends");

    public string this[string key] => key switch
    {
        "label" => Label,
        "short" => Short,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsWeeklyTimeM900Strings : LocalizedStrings, ILabelsWeeklyTimeItem
{
    public string Label => T("10+ saat", "10+ hours");
    public string Short => T("10+ sa", "10+ h");
    public string Hint => T("Bol vakit", "Plenty of time");

    public string this[string key] => key switch
    {
        "label" => Label,
        "short" => Short,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsWeeklyTimeStrings : LocalizedStrings
{
    public LabelsWeeklyTimeM120Strings M120 { get; } = new();
    public LabelsWeeklyTimeM300Strings M300 { get; } = new();
    public LabelsWeeklyTimeM600Strings M600 { get; } = new();
    public LabelsWeeklyTimeM900Strings M900 { get; } = new();

    public ILabelsWeeklyTimeItem this[string key] => key switch
    {
        "120" => M120,
        "300" => M300,
        "600" => M600,
        "900" => M900,
        _ => throw new KeyNotFoundException(key),
    };
}

public sealed class LabelsEffortNoneStrings : LocalizedStrings, ILabelsEffortItem
{
    public string Label => T("Yok", "None");
    public string Hint => T("Oturarak yapılabilir", "Can be done sitting down");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsEffortLightStrings : LocalizedStrings, ILabelsEffortItem
{
    public string Label => T("Hafif", "Light");
    public string Hint => T("Kısa yürüyüş, hafif hareket", "Short walk, light movement");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsEffortModerateStrings : LocalizedStrings, ILabelsEffortItem
{
    public string Label => T("Orta", "Moderate");
    public string Hint => T("Uzun yürüyüş, ayakta etkinlik", "Long walk, standing activity");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsEffortVigorousStrings : LocalizedStrings, ILabelsEffortItem
{
    public string Label => T("Yoğun", "Vigorous");
    public string Hint => T("Koşu, bisiklet, dans", "Running, cycling, dancing");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsEffortStrings : LocalizedStrings
{
    public LabelsEffortNoneStrings None { get; } = new();
    public LabelsEffortLightStrings Light { get; } = new();
    public LabelsEffortModerateStrings Moderate { get; } = new();
    public LabelsEffortVigorousStrings Vigorous { get; } = new();

    public ILabelsEffortItem this[string key] => key switch
    {
        "None" => None,
        "Light" => Light,
        "Moderate" => Moderate,
        "Vigorous" => Vigorous,
        _ => throw new KeyNotFoundException(key),
    };
}

public sealed class LabelsEffortLimitLightStrings : LocalizedStrings, ILabelsEffortLimitItem
{
    public string Label => T("Hafif", "Light");
    public string Hint => T("Yalnızca hafif hareket içeren öneriler", "Only suggestions with light movement");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsEffortLimitModerateStrings : LocalizedStrings, ILabelsEffortLimitItem
{
    public string Label => T("Orta", "Moderate");
    public string Hint => T("Yoğun spor içermeyen öneriler", "Suggestions without intense sport");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsEffortLimitVigorousStrings : LocalizedStrings, ILabelsEffortLimitItem
{
    public string Label => T("Fark etmez", "Doesn't matter");
    public string Hint => T("Her türlü hareket olabilir", "Any kind of movement");

    public string this[string key] => key switch
    {
        "label" => Label,
        "hint" => Hint,
        _ => key,
    };
}

public sealed class LabelsEffortLimitStrings : LocalizedStrings
{
    public LabelsEffortLimitLightStrings Light { get; } = new();
    public LabelsEffortLimitModerateStrings Moderate { get; } = new();
    public LabelsEffortLimitVigorousStrings Vigorous { get; } = new();

    public ILabelsEffortLimitItem this[string key] => key switch
    {
        "Light" => Light,
        "Moderate" => Moderate,
        "Vigorous" => Vigorous,
        _ => throw new KeyNotFoundException(key),
    };
}

public sealed class LabelsNotificationsStrings : LocalizedStrings
{
    public string Off => T("Kapalı", "Off");
    public string WeeklySummary => T("Haftalık özet", "Weekly summary");

    public string this[string key] => key switch
    {
        "Off" => Off,
        "WeeklySummary" => WeeklySummary,
        _ => key,
    };
}

public sealed class LabelsStrings : LocalizedStrings
{
    public LabelsCategoriesStrings Categories { get; } = new();
    public LabelsCategoryDescriptionsStrings CategoryDescriptions { get; } = new();
    public LabelsCostStrings Cost { get; } = new();
    public LabelsRadiusStrings Radius { get; } = new();
    public LabelsQuestTypesStrings QuestTypes { get; } = new();
    public LabelsDifficultiesStrings Difficulties { get; } = new();
    public LabelsStatusesStrings Statuses { get; } = new();
    public LabelsSkipReasonsStrings SkipReasons { get; } = new();
    public LabelsScoreComponentsStrings ScoreComponents { get; } = new();
    public LabelsWeeklyTimeStrings WeeklyTime { get; } = new();
    public LabelsEffortStrings Effort { get; } = new();
    public LabelsEffortLimitStrings EffortLimit { get; } = new();
    public LabelsNotificationsStrings Notifications { get; } = new();
}

public sealed class UiStrings : LocalizedStrings
{
    public string InterestLegendOnce => T("Bir kez dokun: ilgimi çekiyor", "Tap once: interested");
    public string InterestLegendTwice => T("İki kez: çok seviyorum", "Twice: love it");
    public string InterestLove => T("çok seviyorum", "love it");
    public string InterestLike => T("ilgimi çekiyor", "interested");
    public string InterestNone => T("seçili değil", "not selected");
    public string CloseToast => T("Bildirimi kapat", "Dismiss notification");
    public string Rating => T("Deneyim puanı", "Experience rating");
    public string Stars(int n) => T($"{n} yıldız", $"{n} {(n == 1 ? "star" : "stars")}");
    public string Progress => T("İlerleme", "Progress");
}

public sealed class AuthStrings : LocalizedStrings
{
    public string LoginHeading => T("Tekrar hoş geldin", "Welcome back");
    public string LoginLead => T("Bugün gerçek hayatta seni bekleyen küçük maceralar var.", "Small real-life adventures are waiting for you today.");
    public string Email => T("E-posta", "Email");
    public string Password => T("Şifre", "Password");
    public string Login => T("Giriş yap", "Sign in");
    public string NoAccount => T("Hesabın yok mu?", "Don't have an account?");
    public string SignUp => T("Kayıt ol", "Sign up");
    public string EnterCredentials => T("E-posta ve şifreni gir.", "Enter your email and password.");
    public string RegisterHeading => T("Maceraya katıl", "Join the adventure");
    public string RegisterLead => T("Ekran başında değil, gerçek hayatta ilerlediğin bir oyun.", "A game you level up in real life, not in front of a screen.");
    public string DisplayName => T("Sana nasıl hitap edelim?", "What should we call you?");
    public string DisplayNameError => T("En az 2 karakter olmalı.", "Must be at least 2 characters.");
    public string EmailError => T("Geçerli bir e-posta gir.", "Enter a valid email.");
    public string PasswordRule => T("En az 8 karakter; harf ve rakam içermeli.", "At least 8 characters, with letters and numbers.");
    public string BirthYear => T("Doğum yılın", "Your birth year");
    public string BirthYearHint => T("LifeQuest 18 yaş ve üzeri içindir. Yalnızca doğum yılını saklıyoruz.", "LifeQuest is for people aged 18 and over. We only store your birth year.");
    public string CreateAccount => T("Hesap oluştur", "Create account");
    public string HaveAccount => T("Zaten hesabın var mı?", "Already have an account?");

    public string this[string key] => key switch
    {
        "loginHeading" => LoginHeading,
        "loginLead" => LoginLead,
        "email" => Email,
        "password" => Password,
        "login" => Login,
        "noAccount" => NoAccount,
        "signUp" => SignUp,
        "enterCredentials" => EnterCredentials,
        "registerHeading" => RegisterHeading,
        "registerLead" => RegisterLead,
        "displayName" => DisplayName,
        "displayNameError" => DisplayNameError,
        "emailError" => EmailError,
        "passwordRule" => PasswordRule,
        "birthYear" => BirthYear,
        "birthYearHint" => BirthYearHint,
        "createAccount" => CreateAccount,
        "haveAccount" => HaveAccount,
        _ => key,
    };
}

public sealed class OnboardingStrings : LocalizedStrings
{
    public IReadOnlyList<string> Steps => T(new[] { "Hedefler", "İlgi alanları", "Sana göre mi?", "Zaman ve bütçe", "Keşif modu" }, new[] { "Goals", "Interests", "For you?", "Time and budget", "Discovery mode" });
    public string StepOf(int n, int total) => T($"Adım {n} / {total}", $"Step {n} of {total}");
    public string GoalsTitle(string name) => T($"Merhaba{(string.IsNullOrEmpty(name) ? "" : ", " + name)}! Hangi alanlarda ilerlemek istersin?", $"Hi{(string.IsNullOrEmpty(name) ? "" : " " + name)}! Which areas do you want to grow in?");
    public string GoalsLead => T("Life Profile'ın bir kişilik testi değil; yalnızca yaşadığın deneyimleri yansıtır. İstediğin kadar seç, sonra değiştirebilirsin.", "Your Life Profile isn't a personality test; it only reflects the experiences you live. Pick as many as you like and change them later.");
    public string InterestsTitle => T("Neler ilgini çeker?", "What are you into?");
    public string InterestsLead => T("Öneriler buradan başlar ve geri bildirimlerinle zamanla gelişir. En az bir alan seç.", "Suggestions start here and improve over time with your feedback. Pick at least one.");
    public string CardsTitle => T("Bunlardan hangisi sana göre?", "Which of these feel like you?");
    public string CardsLead => T("Birkaç örnek quest'e tepki ver; ilk günden daha isabetli öneriler alırsın. İstersen bu adımı atlayabilirsin.", "React to a few sample quests and get sharper suggestions from day one. You can skip this step.");
    public string NotForMe => T("Bana göre değil", "Not for me");
    public string ForMe => T("Bana göre", "For me");
    public string SkipCard => T("Bu kartı geç", "Skip this card");
    public string Thanks => T("Teşekkürler!", "Thanks!");
    public string LikedCards(int n) => T($"{n} kartı beğendin. İlk önerilerin buna göre şekillenecek.", $"You liked {n} {(n == 1 ? "card" : "cards")}. Your first suggestions will build on that.");
    public string Restart => T("Baştan başla", "Start over");
    public string TimeTitle => T("Haftada ne kadar vaktin var?", "How much time do you have each week?");
    public string BudgetTitle => T("Bütçe yaklaşımın?", "What's your budget like?");
    public string EffortTitle => T("Hareket tercihin?", "How much movement?");
    public string EffortLead => T("Bir hareket kısıtın varsa ya da yoğun sporu sevmiyorsan öneriler buna göre filtrelenir.", "If you have a mobility limit or don't enjoy intense sport, suggestions are filtered accordingly.");
    public string RadiusTitle => T("Ne kadar keşif istersin?", "How much discovery do you want?");
    public string RadiusLead => T("Yeniliğin dozunu sen belirlersin; istediğin zaman değiştirebilirsin.", "You set the dose of novelty; change it any time.");
    public string City => T("Şehir", "City");
    public string Optional => T("(isteğe bağlı)", "(optional)");
    public string CityPlaceholder => T("Ör. İstanbul", "e.g. London");
    public string CityHint => T("Yalnızca şehir gerektiren quest'ler için kullanılır. Konumunu asla takip etmeyiz.", "Only used for quests that need a city. We never track your location.");
    public string Start => T("Maceraya başla", "Start the adventure");
    public string Next => T("Devam", "Continue");
}

public sealed class TodayStrings : LocalizedStrings
{
    public string LevelAria(int level) => T($"Seviye {level}, ilerlemeyi gör", $"Level {level}, see progress");
    public string LevelShort(int level) => T($"Sv. {level}", $"Lv. {level}");
    public string NextLevel => T("Sonraki seviyeye ilerleme", "Progress to next level");
    public string CloseSummary => T("Özeti kapat", "Close summary");
    public string ActiveStrip(int n) => T($"{n} görevin devam ediyor", $"{n} {(n == 1 ? "quest" : "quests")} in progress");
    public string SavedStrip(int n) => T($"\"Sonra yaparım\" listende {n} deneyim var", $"{n} {(n == 1 ? "experience" : "experiences")} on your \"Later\" list");
    public string Suggestions => T("Bugünün önerileri", "Today's suggestions");
    public string LoadFailed => T("Öneriler yüklenemedi", "Couldn't load suggestions");
    public string AllDone => T("Bugünün önerilerini tamamladın", "You've done today's suggestions");
    public string AllDoneHint(string hour) => T($"Yeni öneriler yarın sabah {hour}:00'da gelir. Beklemek istemezsen aşağıdan boş vaktine göre öneri alabilirsin.", $"New suggestions arrive tomorrow at {hour}:00. If you don't want to wait, get suggestions for your free time below.");
    public string None => T("Bugün için öneri yok", "No suggestions for today");
    public string EditPreferences => T("Tercihlerimi düzenle", "Edit my preferences");
    public string CompletedToday => T("Bugün tamamladıkların", "Completed today");
    public string FreeTime => T("Boş vaktin mi var?", "Got some free time?");
    public string FreeTimeHint => T("Ne kadar zamanın olduğunu söyle, ona göre önerelim.", "Tell us how much time you have and we'll suggest something.");
}

public sealed class SuggestOptionsStrings : LocalizedStrings
{
    public string M30 => T("30 dk", "30 min");
    public string M60 => T("1 sa", "1 h");
    public string M120 => T("2 sa", "2 h");
    public string M180 => T("3 sa+", "3 h+");

    public string this[string key] => key switch
    {
        "30" => M30,
        "60" => M60,
        "120" => M120,
        "180" => M180,
        _ => key,
    };
}

public sealed class SuggestStrings : LocalizedStrings
{
    public string Back => T("Bugün", "Today");
    public string Title => T("Ne kadar vaktin var?", "How much time do you have?");
    public string Lead => T("Bu ana uygun, gerçek hayatta yapabileceğin öneriler getirelim.", "Let's find real-life things you can do right now.");
    public string Duration => T("Süre", "Duration");
    public string Budget => T("Bütçe", "Budget");
    public string Submit => T("Öner", "Suggest");
    public SuggestOptionsStrings Options { get; } = new();
    public string LimitTitle => T("Bugünlük bu kadar", "That's it for today");
    public string LimitMessage => T("Bugünkü bağlamsal öneri hakkını kullandın. Günün önerileri seni bekliyor.", "You've used today's on-demand suggestions. Today's suggestions are waiting for you.");
    public string Todays => T("Bugünün önerileri", "Today's suggestions");
    public string ForYou => T("Sana özel öneriler", "Suggestions for you");
    public string NoneTitle => T("Uygun öneri bulamadık", "We couldn't find a fitting suggestion");
}

public sealed class QuestsStrings : LocalizedStrings
{
    public string Title => T("Görevlerim", "My quests");
    public string ListAria => T("Görev listesi", "Quest list");
    public string TabActive => T("Devam eden", "In progress");
    public string TabHistory => T("Geçmiş", "History");
    public string LoadFailed => T("Görevler yüklenemedi", "Couldn't load quests");
    public string NoneActive => T("Devam eden görevin yok", "No quests in progress");
    public string NoneActiveHint => T("Bugünün önerilerinden birini kabul ederek başlayabilirsin.", "Accept one of today's suggestions to get started.");
    public string Browse => T("Önerilere göz at", "Browse suggestions");
    public string FilterAria => T("Duruma göre filtrele", "Filter by status");
    public string FilterAll => T("Tümü", "All");
    public string FilterCompleted => T("Tamamlanan", "Completed");
    public string FilterSkipped => T("Geçilen", "Skipped");
    public string FilterExpired => T("Süresi dolan", "Expired");
    public string NoHistory => T("Henüz kayıt yok", "Nothing here yet");
    public string LoadMore => T("Daha fazla yükle", "Load more");

    public string this[string key] => key switch
    {
        "title" => Title,
        "listAria" => ListAria,
        "tabActive" => TabActive,
        "tabHistory" => TabHistory,
        "loadFailed" => LoadFailed,
        "noneActive" => NoneActive,
        "noneActiveHint" => NoneActiveHint,
        "browse" => Browse,
        "filterAria" => FilterAria,
        "filterAll" => FilterAll,
        "filterCompleted" => FilterCompleted,
        "filterSkipped" => FilterSkipped,
        "filterExpired" => FilterExpired,
        "noHistory" => NoHistory,
        "loadMore" => LoadMore,
        _ => key,
    };
}

public sealed class QuestFactsStrings : LocalizedStrings
{
    public string Duration => T("Süre", "Duration");
    public string Cost => T("Maliyet", "Cost");
    public string Difficulty => T("Zorluk", "Difficulty");
    public string Type => T("Tür", "Type");
    public string Effort => T("Efor", "Effort");

    public string this[string key] => key switch
    {
        "duration" => Duration,
        "cost" => Cost,
        "difficulty" => Difficulty,
        "type" => Type,
        "effort" => Effort,
        _ => key,
    };
}

public sealed class QuestStrings : LocalizedStrings
{
    public string NotFound => T("Quest bulunamadı", "Quest not found");
    public string NotFoundHint => T("Bu quest artık mevcut değil ya da sana ait değil.", "This quest no longer exists or isn't yours.");
    public string BackToToday => T("Bugüne dön", "Back to today");
    public string Exploration => T("Keşif önerisi", "Discovery pick");
    public QuestFactsStrings Facts { get; } = new();
    public string Reward => T("Ödül", "Reward");
    public string Why => T("Neden bunu önerdik?", "Why did we suggest this?");
    public string ScoreAria => T("Öneri skoru bileşenleri", "Recommendation score components");
    public string ScoreFoot => T("Skorlar 0–100 arasıdır. Kırmızı çubuklar öneriyi aşağı çeken etkenlerdir.", "Scores range from 0 to 100. Red bars are factors pulling the suggestion down.");
    public string Nearby => T("Şehrinde", "In your city");
    public string Details => T("Ayrıntılar", "Details");
    public string OfferedHint => T("Kabul ettiğinde tamamlamak için sana zaman tanınır; kaçırmanın bir cezası yok.", "Once you accept, you get time to complete it; there's no penalty for missing it.");
    public string InProgress(string remaining) => T($"Devam ediyor · {remaining}", $"In progress · {remaining}");
    public string CompletedOn(string date) => T($"{date} tarihinde tamamladın.", $"You completed it on {date}.");
    public string YourRating(int n) => T($"Puanın: {n} / 5", $"Your rating: {n} / 5");
    public string HowWasIt => T("Deneyim nasıldı?", "How was it?");
    public string SaveRating => T("Puanı kaydet", "Save rating");
    public string Later => T("Sonra yaparım", "Later");
    public string Plan => T("Planla", "Plan");
    public string ChangePlan => T("Planı değiştir", "Change plan");
    public string AddToCalendar => T("Takvime ekle", "Add to calendar");
    public string PlannedFor(string when) => T($"{when} için planladın", $"Planned for {when}");
    public string Skip => T("Geç", "Skip");
    public string Drop => T("Bırak", "Drop");
    public string Accept => T("Kabul et", "Accept");
    public string Done => T("Tamamladım", "I did it");
    public string PlanTitle => T("Ne zaman yapacaksın?", "When will you do it?");
    public string PlanHint => T("Kendi takvimine eklemen için bir zaman seç. Hatırlatma göndermeyiz; dosyayı takvimine eklersen takvimin hatırlatır.", "Pick a time to add to your own calendar. We don't send reminders; your calendar will remind you if you add the file.");
    public string DateTime => T("Tarih ve saat", "Date and time");
    public string SavePlan => T("Planı kaydet", "Save plan");
    public string RemovePlan => T("Planı kaldır", "Remove plan");
    public string SkipTitle => T("Neden geçiyorsun?", "Why are you skipping?");
    public string SkipHint => T("Cevabın önerileri iyileştirir. \"Pahalı\" veya \"zamanım yok\" ilgi alanlarını etkilemez.", "Your answer improves suggestions. \"Too expensive\" or \"No time\" don't affect your interests.");
    public string Confirm => T("Onayla", "Confirm");
    public string ToastAccepted => T("Quest kabul edildi. Keyfini çıkar!", "Quest accepted. Enjoy!");
    public string ToastSkipped => T("Geçildi. Geri bildirimin sonraki önerileri şekillendirecek.", "Skipped. Your feedback will shape the next suggestions.");
    public string ToastSaved => T("\"Sonra yaparım\" listene eklendi. Hazır olduğunda oradan başlatabilirsin.", "Added to your \"Later\" list. Start it from there when you're ready.");
    public string ToastPlanned => T("Planlandı. \"Takvime ekle\" ile kendi takvimine koyabilirsin.", "Planned. Use \"Add to calendar\" to put it in your own calendar.");
    public string ToastPlanRemoved => T("Plan kaldırıldı.", "Plan removed.");
    public string ToastAchievement(string title) => T($"Yeni başarım: {title}", $"New achievement: {title}");
    public string ToastThanks => T("Teşekkürler! Önerilerin buna göre gelişecek.", "Thanks! Your suggestions will improve based on this.");
}

public sealed class CelebrationStrings : LocalizedStrings
{
    public string AlreadyDone => T("Bu quest zaten tamamlanmış", "This quest was already completed");
    public string Great => T("Harika, tamamladın!", "Great, you did it!");
    public string PartyBonus(int xp) => T($"Parti tamamlandı: +{xp} \"birlikte\" XP!", $"Party complete: +{xp} \"together\" XP!");
    public string LevelUp(int level) => T($"Seviye {level}'e ulaştın!", $"You reached level {level}!");
    public string NewAchievement => T("Yeni başarım:", "New achievement:");
    public string HowWasIt => T("Deneyim nasıldı?", "How was it?");
    public string Similar => T("Benzer öneriler", "Similar suggestions");
    public string More => T("Daha fazla göster", "Show more like this");
    public string Less => T("Daha az göster", "Show less like this");
    public string SaveContinue => T("Kaydet ve devam et", "Save and continue");
    public string Continue => T("Devam et", "Continue");
}

public sealed class PartyStrings : LocalizedStrings
{
    public string Together => T("Birlikte yap", "Do it together");
    public string Completed => T("Parti tamamlandı! Tamamlayan herkes \"birlikte\" XP'si kazandı.", "Party complete! Everyone who finished earned \"together\" XP.");
    public string You => T("(sen)", "(you)");
    public string Host => T("· kurucu", "· host");
    public string Done => T("tamamladı", "done");
    public string Dropped => T("bıraktı", "dropped out");
    public string InProgress => T("görevde", "in progress");
    public string ShareHint(int n, int max) => T($"Bağlantıyı paylaş: {n}/{max} kişi. Herkes kendi görevini yapar; partide kalan herkes tamamlayınca bonus gelir.", $"Share the link: {n}/{max} people. Everyone does their own quest; once everyone still in finishes, the bonus arrives.");
    public string InviteLink => T("Davet bağlantısı", "Invite link");
    public string Share => T("Paylaş", "Share");
    public string Copy => T("Kopyala", "Copy");
    public string InviteHint => T("Bir arkadaşını davet et: ikiniz de görevi tamamlayınca ekstra \"birlikte\" XP'si kazanırsınız.", "Invite a friend: when you both complete the quest, you each earn extra \"together\" XP.");
    public string CreateLink => T("Davet bağlantısı oluştur", "Create invite link");
    public string ShareText(string title) => T($"\"{title}\" görevini birlikte yapalım mı? LifeQuest'te partime katıl:", $"Shall we do \"{title}\" together? Join my party on LifeQuest:");
    public string Copied => T("Bağlantı kopyalandı.", "Link copied.");
    public string OpenFailed => T("Davet açılamadı", "Couldn't open the invite");
    public string BackToToday => T("Bugüne dön", "Back to today");
    public string Invites(string host) => T($"{host} seni birlikte yapmaya çağırıyor", $"{host} invites you to do this together");
    public string Summary(int n, int max, string until) => T($"{n}/{max} kişi · {until} tarihine kadar.", $"{n}/{max} people · until {until}.");
    public string Rules => T("Herkes kendi görevini kendi yapar; partide kalan herkes tamamlayınca tamamlayanlar ekstra \"birlikte\" XP'si kazanır.", "Everyone does their own quest; once everyone still in the party finishes, those who finished earn extra \"together\" XP.");
    public string GoToQuest => T("Görevine git", "Go to your quest");
    public string Join => T("Katıl", "Join");
    public string JoinHint => T("Katılınca görev aktif görevlerine eklenir. Diğer üyeler yalnızca görünen adını ve görevi tamamlayıp tamamlamadığını görür.", "Joining adds the quest to your active quests. Other members only see your display name and whether you finished.");
    public string Closed => T("Bu parti artık katılıma açık değil.", "This party is no longer open to join.");
    public string Joined => T("Partiye katıldın. Görev aktif görevlerine eklendi.", "You joined the party. The quest was added to your active quests.");
}

public sealed class SavedStrings : LocalizedStrings
{
    public string Title => T("Sonra yaparım", "Later");
    public string Lead => T("Şimdi olmasa da kaçırmak istemediğin deneyimler. Başlattığında aktif görevlerine eklenir.", "Experiences you don't want to miss, even if not right now. Starting one adds it to your active quests.");
    public string LoadFailed => T("Liste yüklenemedi", "Couldn't load the list");
    public string Unavailable => T("Bu deneyim şu an katalogda sunulmuyor.", "This experience isn't offered in the catalog right now.");
    public string StartNow => T("Şimdi başla", "Start now");
    public string EmptyTitle => T("Listen boş", "Your list is empty");
    public string EmptyHint => T("Bir önerinin detayında \"Sonra yaparım\"a dokunarak buraya ekleyebilirsin.", "Tap \"Later\" on a suggestion's details to add it here.");
    public string Browse => T("Önerilere göz at", "Browse suggestions");
    public string Started => T("Başladı! Aktif görevlerine eklendi.", "Started! Added to your active quests.");

    public string this[string key] => key switch
    {
        "title" => Title,
        "lead" => Lead,
        "loadFailed" => LoadFailed,
        "unavailable" => Unavailable,
        "startNow" => StartNow,
        "emptyTitle" => EmptyTitle,
        "emptyHint" => EmptyHint,
        "browse" => Browse,
        "started" => Started,
        _ => key,
    };
}

public sealed class ProgressStrings : LocalizedStrings
{
    public string Title => T("İlerleme", "Progress");
    public string LoadFailed => T("İlerleme yüklenemedi", "Couldn't load progress");
    public string ToNext(int xp) => T($"Sonraki seviyeye {xp} XP", $"{xp} XP to the next level");
    public string Experiences(int n) => T($"{n} gerçek deneyim", $"{n} real-life {(n == 1 ? "experience" : "experiences")}");
    public string ProfileLead => T("Seviyeler bir kişilik testi değil; yalnızca yaşadığın deneyimleri yansıtır.", "Levels aren't a personality test; they only reflect the experiences you live.");
    public string LevelLine(int level, int xp, int next) => T($"Sv. {level} · {xp} / {next} XP", $"Lv. {level} · {xp} / {next} XP");
    public string CategoryProgress(string name) => T($"{name} ilerlemesi", $"{name} progress");
    public string Achievements => T("Başarımlar", "Achievements");
    public string Unlocked => T("açıldı", "unlocked");
    public string Locked => T("kilitli", "locked");
    public string Recent => T("Son kazanımlar", "Recent gains");
}

public sealed class IdeasStatusStrings : LocalizedStrings
{
    public string Pending => T("İnceleniyor", "In review");
    public string Accepted => T("Kataloğa eklendi", "Added to catalog");
    public string Rejected => T("Eklenmedi", "Not added");

    public string this[string key] => key switch
    {
        "Pending" => Pending,
        "Accepted" => Accepted,
        "Rejected" => Rejected,
        _ => key,
    };
}

public sealed class IdeasStrings : LocalizedStrings
{
    public string Title => T("Bir deneyim öner", "Suggest an experience");
    public string Lead => T("Başkalarının da sevebileceği küçük bir gerçek hayat deneyimi mi var? Paylaş; ekibimiz inceleyip güvenlik kurallarına uygunsa kataloğa ekler. Kimliğin deneyimle birlikte paylaşılmaz.", "Have a small real-life experience others might love too? Share it; our team reviews it and adds it to the catalog if it meets the safety rules. Your identity isn't shared with it.");
    public string TitleLabel => T("Başlık", "Title");
    public string TitlePlaceholder => T("Örn. Mahalle kütüphanesi turu", "e.g. Neighborhood library tour");
    public string Description => T("Ne yapılıyor?", "What do you do?");
    public string DescriptionPlaceholder => T("Deneyimi kendi cümlelerinle anlat. Bağlantı, e-posta veya telefon ekleme.", "Describe the experience in your own words. Don't add links, emails or phone numbers.");
    public string MinChars => T("en az 30 karakter", "at least 30 characters");
    public string Area => T("Alan", "Area");
    public string Minutes => T("Yaklaşık süre (dk)", "Approx. duration (min)");
    public string Cost => T("Maliyet", "Cost");
    public string Outdoor => T("Açık havada yapılır", "Done outdoors");
    public string Submit => T("Fikri gönder", "Send idea");
    public string Mine => T("Fikirlerim", "My ideas");
    public string Withdraw => T("Geri çek", "Withdraw");
    public string EmptyTitle => T("Henüz fikir göndermedin", "You haven't sent any ideas yet");
    public string EmptyHint => T("İlk fikrin kataloğa eklenen ilk topluluk deneyimi olabilir.", "Your first idea could be the first community experience in the catalog.");
    public IdeasStatusStrings Status { get; } = new();
    public string Sent => T("Teşekkürler! Fikrin incelemeye alındı.", "Thanks! Your idea is now in review.");
}

public sealed class ProfileThemesStrings : LocalizedStrings
{
    public string System => T("Sistem", "System");
    public string Light => T("Açık", "Light");
    public string Dark => T("Koyu", "Dark");

    public string this[string key] => key switch
    {
        "system" => System,
        "light" => Light,
        "dark" => Dark,
        _ => key,
    };
}

public sealed class ProfileStrings : LocalizedStrings
{
    public string Discovery => T("Keşif tercihleri", "Discovery preferences");
    public string Mode => T("Keşif modu", "Discovery mode");
    public string Budget => T("Bütçe", "Budget");
    public string WeeklyTime => T("Haftalık zaman", "Weekly time");
    public string Movement => T("Hareket tercihi", "Movement preference");
    public string MovementHint => T("Bu seviyenin üzerindeki hareket gerektiren quest'ler önerilmez.", "Quests needing more movement than this level are not suggested.");
    public string Notifications => T("Bildirimler", "Notifications");
    public string NotificationsHint => T("Haftalık özet uygulamada görünür; bildirim izni verdiysen telefonuna da gelir.", "The weekly summary appears in the app; if you allowed notifications, it also reaches your phone.");
    public string Goals => T("Hedef alanların", "Your goal areas");
    public string City => T("Şehir", "City");
    public string Optional => T("(isteğe bağlı)", "(optional)");
    public string CityPlaceholder => T("Ör. İzmir", "e.g. Manchester");
    public string Interests => T("İlgi alanların", "Your interests");
    public string InterestsHint => T("Geri bildirimlerinden öğrendiklerimiz \"öğrenildi\" olarak işaretlenir.", "What we learned from your feedback is marked \"learned\".");
    public string Learned => T("öğrenildi", "learned");
    public string InterestLevel(string pct) => T($"İlgi düzeyi yüzde {pct}", $"Interest level {pct} percent");
    public string Appearance => T("Dil ve görünüm", "Language and appearance");
    public string Theme => T("Tema", "Theme");
    public ProfileThemesStrings Themes { get; } = new();
    public string LanguageHint => T("Push bildirimleri ve haftalık özet de bu dilde gelir.", "Push notifications and the weekly summary also come in this language.");
    public string Account => T("Hesap", "Account");
    public string SavedList => T("Sonra yaparım listem", "My \"Later\" list");
    public string SuggestIdea => T("Bir deneyim öner", "Suggest an experience");
    public string ExportData => T("Verilerimi indir", "Download my data");
    public string ExportHint => T("Tüm verilerin (profil, görevler, XP, özetler) JSON dosyası olarak iner. Saatte en fazla 3 kez.", "All your data (profile, quests, XP, summaries) downloads as a JSON file. At most 3 times an hour.");
    public string Admin => T("Yönetim paneli", "Admin panel");
    public string Logout => T("Çıkış yap", "Sign out");
    public string DeleteAccount => T("Hesabımı sil", "Delete my account");
    public string EditInterests => T("İlgi alanlarını düzenle", "Edit your interests");
    public string DeleteTitle => T("Hesabını sil", "Delete your account");
    public string DeleteWarning => T("Hesabın, quest geçmişin, XP'lerin ve tüm tercihlerin kalıcı olarak silinecek. Bu işlem geri alınamaz.", "Your account, quest history, XP and all preferences will be deleted permanently. This cannot be undone.");
    public string DeletePassword => T("Onaylamak için şifreni gir", "Enter your password to confirm");
    public string DeleteForever => T("Kalıcı olarak sil", "Delete permanently");
    public string SavedPrefs => T("Tercihlerin kaydedildi. Yarınki öneriler buna göre şekillenecek.", "Preferences saved. Tomorrow's suggestions will follow them.");
    public string PickInterest => T("En az bir ilgi alanı seçmelisin.", "Pick at least one interest.");
    public string InterestsSaved => T("İlgi alanların güncellendi.", "Your interests were updated.");
    public string Deleted => T("Hesabın ve tüm verilerin silindi.", "Your account and all your data were deleted.");
    public string Exported => T("Verilerin indirildi.", "Your data was downloaded.");
    public string ExportFile => T("lifequest-verilerim.json", "lifequest-my-data.json");
}

public sealed class ReminderStrings : LocalizedStrings
{
    public string Title => T("Günlük hatırlatma", "Daily reminder");
    public string Active(string time) => T($"Her gün {time}'de, o gün görev tamamlamadıysan kısa bir hatırlatma gelir.", $"Every day at {time}, a short reminder arrives if you haven't completed a quest that day.");
    public string Off => T("Kapalı. Açarsan seçtiğin saatte, günde en fazla bir kez hatırlatırız. O gün görev tamamladıysan rahatsız etmeyiz.", "Off. Turn it on and we'll remind you at your chosen time, at most once a day. If you've already completed a quest that day, we won't bother you.");
    public string Hour => T("Hatırlatma saati", "Reminder time");
    public string Enable => T("Hatırlatmayı aç", "Turn on reminder");
    public string SaveTime => T("Saati kaydet", "Save time");
    public string Test => T("Deneme bildirimi gönder", "Send a test notification");
    public string Disable => T("Hatırlatmayı kapat", "Turn off reminder");
    public string Unsupported => T("Bu tarayıcıda anlık bildirim yok. iPhone ve iPad'de önce LifeQuest'i Paylaş → Ana Ekrana Ekle ile yükle.", "This browser has no push notifications. On iPhone and iPad, first install LifeQuest via Share → Add to Home Screen.");
    public string Denied => T("Bildirim izni kapalı. Tarayıcının site ayarlarından LifeQuest için bildirimlere izin verip tekrar dene.", "Notification permission is off. Allow notifications for LifeQuest in your browser's site settings and try again.");
    public string ServerDisabled => T("Anlık bildirimler bu sunucuda henüz etkin değil.", "Push notifications aren't enabled on this server yet.");
    public string Enabled(string time) => T($"Hatırlatma her gün {time}'de.", $"Reminder set for {time} every day.");
    public string Disabled => T("Günlük hatırlatma kapatıldı.", "Daily reminder turned off.");
    public string TestSent => T("Deneme bildirimi gönderildi.", "Test notification sent.");
}
