// Web ikon setini (src/LifeQuest.Web/src/app/ui/icon.ts) mobil için tek yol verisine çevirir.
// Çıktı: src/LifeQuest.Mobile.Core/Formatting/Icons.g.cs — 24×24 çizgi ikonları, MAUI Path.Data söz dizimiyle.
// Çalıştırma: node tools/mobile/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const source = readFileSync(join(root, 'src/LifeQuest.Web/src/app/ui/icon.ts'), 'utf8');
const consts = [...source.matchAll(/^const (\w+) = ([\s\S]*?)(?: satisfies [^;]+)?;$/gm)].map((m) => `const ${m[1]} = ${m[2]};`);
const icons = new Function(`${consts.join('\n')}\nreturn ICONS;`)();

const n = (v) => +v.toFixed(3);

// MAUI'nin yol ayrıştırıcısı örtük komutları (ör. "M1 2 3 4" → M1 2 L3 4) tanımıyor: her parametre grubu kendi
// komutuyla yazılır.
const ARITY = { m: 2, l: 2, h: 1, v: 1, c: 6, s: 4, q: 4, t: 2, a: 7, z: 0 };
function explicit(d) {
  const tokens = d.match(/[a-zA-Z]|-?(?:\d+\.?\d*|\.\d+)(?:e-?\d+)?/g);
  const out = [];
  let i = 0;
  while (i < tokens.length) {
    let cmd = tokens[i++];
    const arity = ARITY[cmd.toLowerCase()];
    if (arity === 0) { out.push(cmd); continue; }
    let first = true;
    while (i < tokens.length && !/[a-zA-Z]/.test(tokens[i])) {
      const args = tokens.slice(i, i + arity);
      i += arity;
      out.push((first ? cmd : cmd === 'M' ? 'L' : cmd === 'm' ? 'l' : cmd) + args.join(' '));
      first = false;
    }
  }
  return out.join(' ');
}
const circle = ([cx, cy, r]) => `M${n(cx - r)} ${cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0z`;
const rect = ([x, y, w, h, rx]) =>
  `M${x + rx} ${y}h${w - 2 * rx}a${rx} ${rx} 0 0 1 ${rx} ${rx}v${h - 2 * rx}a${rx} ${rx} 0 0 1 ${-rx} ${rx}` +
  `h${-(w - 2 * rx)}a${rx} ${rx} 0 0 1 ${-rx} ${-rx}v${-(h - 2 * rx)}a${rx} ${rx} 0 0 1 ${rx} ${-rx}z`;

const entries = Object.entries(icons).map(([name, shape]) => {
  const data = [...(shape.paths ?? []), ...(shape.circles ?? []).map(circle), ...(shape.rects ?? []).map(rect)].map(explicit).join(' ');
  const rotated = shape.transform === 'rotate(180 12 12)';
  if (shape.transform && !rotated) throw new Error(`${name}: desteklenmeyen dönüşüm ${shape.transform}`);
  return `        ["${name}"] = new("${data}", ${rotated}),`;
});

writeFileSync(join(root, 'src/LifeQuest.Mobile.Core/Formatting/Icons.g.cs'), `// <auto-generated>
// tools/mobile/gen-icons.mjs tarafından web ikon setinden (ui/icon.ts) üretildi. Elle düzenlemeyin.
// </auto-generated>
namespace LifeQuest.Mobile.Core.Formatting;

/// <summary>24×24 çizgi ikonu: SVG yol verisi; <see cref="Rotated"/> ise 180° döndürülerek çizilir.</summary>
public sealed record IconShape(string Data, bool Rotated);

public static class Icons
{
    public static IReadOnlyDictionary<string, IconShape> All { get; } = new Dictionary<string, IconShape>
    {
${entries.join('\n')}
    };

    public static IconShape Get(string? name) => name is not null && All.TryGetValue(name, out var shape) ? shape : All["info"];
}
`);
console.log(`${entries.length} ikon`);
