using LifeQuest.Domain.Catalog;
using LifeQuest.Domain.Common;
using static LifeQuest.Domain.Common.DayPart;
using E = LifeQuest.Domain.Catalog.PhysicalEffort;

namespace LifeQuest.Infrastructure.Persistence.Seed;

/// <summary>
/// Editoryal katalog: 100 güvenli template (kategori başına 16-17). Hepsi 18+, fotoğraf/konum doğrulaması
/// gerektirmez ve <see cref="CatalogSafetyRules"/> kontrol listesinden geçer (LifeQuest.Catalog.Tests CI kapısı).
/// Seed editoryal kaynaktır: mevcut template'ler buradaki tanıma göre güncellenir, değişen template'in sürümü artar.
/// </summary>
internal static class CatalogSeedData
{
    public sealed record InterestSeed(string Code, string Name, LifeCategory Category);

    public sealed record RelationSeed(string From, string To, double Weight, InterestRelationType Type = InterestRelationType.Adjacent);

    public sealed record TemplateSeed(
        string Code, string Title, string Description,
        QuestType Type, Difficulty Difficulty, LifeCategory Category, LifeCategory? Secondary,
        int MinMinutes, int MaxMinutes, CostBand Cost, DayPart DayParts,
        bool RequiresCity, bool IsOutdoor, int CooldownDays, double Risk, string[] Interests,
        E Effort, bool Starter = false);

    public static readonly InterestSeed[] Interests =
    [
        new("coffee", "Kahve", LifeCategory.Explorer),
        new("cafe-culture", "Kafe Kültürü", LifeCategory.Explorer),
        new("neighborhoods", "Semt Keşfi", LifeCategory.Explorer),
        new("street-food", "Sokak Lezzetleri", LifeCategory.Explorer),
        new("nature", "Doğa", LifeCategory.Explorer),
        new("local-markets", "Yerel Pazarlar", LifeCategory.Explorer),

        new("museums", "Müzeler", LifeCategory.Culture),
        new("art", "Sanat", LifeCategory.Culture),
        new("cinema", "Sinema", LifeCategory.Culture),
        new("theatre", "Tiyatro", LifeCategory.Culture),
        new("architecture", "Mimari", LifeCategory.Culture),
        new("history", "Tarih", LifeCategory.Culture),
        new("live-music", "Canlı Müzik", LifeCategory.Culture),

        new("reading", "Okuma", LifeCategory.Learning),
        new("languages", "Yabancı Dil", LifeCategory.Learning),
        new("science", "Bilim", LifeCategory.Learning),
        new("podcasts", "Podcast", LifeCategory.Learning),
        new("cooking", "Yemek Yapma", LifeCategory.Learning),
        new("astronomy", "Astronomi", LifeCategory.Learning),

        new("friends", "Arkadaşlar", LifeCategory.Social),
        new("volunteering", "Gönüllülük", LifeCategory.Social),
        new("board-games", "Kutu Oyunları", LifeCategory.Social),
        new("community-events", "Topluluk Etkinlikleri", LifeCategory.Social),

        new("walking", "Yürüyüş", LifeCategory.Fitness),
        new("running", "Koşu", LifeCategory.Fitness),
        new("cycling", "Bisiklet", LifeCategory.Fitness),
        new("yoga", "Yoga", LifeCategory.Fitness),
        new("swimming", "Yüzme", LifeCategory.Fitness),
        new("meditation", "Meditasyon", LifeCategory.Fitness),
        new("dance", "Dans", LifeCategory.Fitness),

        new("photography", "Fotoğrafçılık", LifeCategory.Creativity),
        new("street-photography", "Sokak Fotoğrafçılığı", LifeCategory.Creativity),
        new("drawing", "Çizim", LifeCategory.Creativity),
        new("writing", "Yazarlık", LifeCategory.Creativity),
        new("music-making", "Müzik Yapma", LifeCategory.Creativity),
        new("crafts", "El Sanatları", LifeCategory.Creativity),
        new("gardening", "Bahçecilik", LifeCategory.Creativity)
    ];

    /// <summary>Taste Graph: Kahve → Kafe Kültürü → Mimari → Fotoğrafçılık → Sokak Fotoğrafçılığı gibi geçişler.</summary>
    public static readonly RelationSeed[] Relations =
    [
        new("coffee", "cafe-culture", 0.9),
        new("cafe-culture", "architecture", 0.5),
        new("architecture", "photography", 0.6),
        new("photography", "street-photography", 0.8, InterestRelationType.Specialization),
        new("neighborhoods", "architecture", 0.6),
        new("neighborhoods", "street-photography", 0.5),
        new("cinema", "theatre", 0.6),
        new("cinema", "writing", 0.4),
        new("art", "museums", 0.7),
        new("art", "drawing", 0.6),
        new("museums", "history", 0.7),
        new("history", "architecture", 0.6),
        new("reading", "writing", 0.6),
        new("reading", "podcasts", 0.5),
        new("cooking", "street-food", 0.5),
        new("street-food", "local-markets", 0.7),
        new("walking", "nature", 0.7),
        new("walking", "photography", 0.4),
        new("running", "walking", 0.6),
        new("live-music", "music-making", 0.5),
        new("board-games", "friends", 0.6),
        new("volunteering", "community-events", 0.7),
        new("languages", "podcasts", 0.4),
        new("science", "museums", 0.4),
        new("yoga", "walking", 0.3),
        new("cycling", "nature", 0.6),
        new("crafts", "drawing", 0.5),
        new("yoga", "meditation", 0.7),
        new("dance", "live-music", 0.6),
        new("dance", "friends", 0.4),
        new("gardening", "nature", 0.6),
        new("gardening", "cooking", 0.4),
        new("astronomy", "science", 0.7),
        new("astronomy", "nature", 0.5)
    ];

    private const DayPart Daytime = Morning | Afternoon;
    private const DayPart Waking = Morning | Afternoon | Evening;

    public static readonly TemplateSeed[] Templates =
    [
        // ── Keşif (Explorer) · 17 ─────────────────────────────────────────────
        new("explorer-new-street", "Hiç yürümediğin bir sokaktan geç",
            "Bugün alışık olduğun rotadan bir sokak sap ve dikkatini çeken üç detayı not et.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Explorer, LifeCategory.Fitness,
            10, 20, CostBand.Free, Waking, false, true, 3, 0, ["neighborhoods", "walking"], E.Light, Starter: true),
        new("explorer-map-walk", "Haritadan rastgele bir sokak seç",
            "Haritayı aç, bulunduğun semtte hiç görmediğin bir sokağı seç ve oraya kısa bir yürüyüş yap.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Explorer, LifeCategory.Fitness,
            20, 30, CostBand.Free, Waking, false, true, 3, 0, ["neighborhoods", "walking"], E.Light),
        new("explorer-local-bakery", "Mahalle fırınının bir özel ürününü dene",
            "Yakınındaki bir fırında daha önce almadığın bir ürünü dene ve tadını birkaç kelimeyle not et.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Explorer, null,
            10, 20, CostBand.Low, Daytime, false, false, 3, 0, ["street-food"], E.Light),
        new("explorer-coffee-brew", "Farklı bir demleme yöntemiyle kahve",
            "Evde ya da bir kafede daha önce denemediğin bir demleme yöntemini (French press, cezve, filtre) dene.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Explorer, LifeCategory.Learning,
            15, 25, CostBand.Low, Daytime, false, false, 7, 0, ["coffee"], E.None),
        new("explorer-new-cafe", "Yeni bir kafe keşfet",
            "Daha önce hiç gitmediğin bir kafeye git ve menüde ilk kez denediğin bir şey sipariş et.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, null,
            45, 90, CostBand.Low, Waking, true, false, 7, 0, ["coffee", "cafe-culture"], E.Light, Starter: true),
        new("explorer-local-market", "Semt pazarını gez",
            "Bir semt pazarını dolaş ve daha önce tatmadığın bir ürünü dene.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, null,
            60, 120, CostBand.Low, Daytime, true, true, 14, 0, ["local-markets", "street-food"], E.Light),
        new("explorer-neighborhood", "Hiç gitmediğin bir semti keşfet",
            "Şehrinde hiç vakit geçirmediğin bir semte git; bir meydan, bir yapı ve bir mekân keşfet.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Explorer, LifeCategory.Culture,
            90, 180, CostBand.Low, Daytime, true, true, 14, 0, ["neighborhoods", "architecture"], E.Moderate),
        new("explorer-street-food", "Yeni bir sokak lezzeti tat",
            "Daha önce denemediğin yöresel bir sokak lezzetini bul ve tat.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, null,
            45, 90, CostBand.Low, Afternoon | Evening, true, false, 7, 0, ["street-food"], E.Light),
        new("explorer-sunrise", "Gün doğumunu açık havada izle",
            "Erken kalk, güvenli ve bildiğin bir noktadan gün doğumunu izle.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, LifeCategory.Creativity,
            30, 60, CostBand.Free, Morning, false, true, 14, 0, ["nature", "photography"], E.Light),
        new("explorer-bookstore", "Bağımsız bir kitabevini keşfet",
            "Daha önce girmediğin bağımsız bir kitabevinde dolaş, rafları incele ve kendine bir kitap önerisi al.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, LifeCategory.Learning,
            45, 90, CostBand.Low, Waking, true, false, 14, 0, ["neighborhoods", "reading"], E.Light),
        new("explorer-breakfast-spot", "Yeni bir kahvaltı mekânı dene",
            "Hiç gitmediğin bir kahvaltı mekânında güne başla; menüdeki yöresel bir lezzeti tercih et.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, null,
            60, 120, CostBand.Medium, Morning, true, false, 14, 0, ["street-food", "cafe-culture"], E.Light),
        new("explorer-new-park", "Hiç gitmediğin bir parkta mola ver",
            "Şehrinde daha önce uğramadığın bir parkı bul, bir bank seç ve çevreyi on beş dakika sadece gözlemle.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, null,
            30, 60, CostBand.Free, Daytime, true, true, 14, 0, ["nature", "neighborhoods"], E.Light),
        new("explorer-transit-route", "Toplu taşımayla yeni bir rota",
            "Hiç kullanmadığın bir toplu taşıma hattına (vapur, tramvay, otobüs) bin ve son durakta kısa bir keşif yap.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Explorer, null,
            90, 180, CostBand.Low, Daytime, true, false, 21, 0.05, ["neighborhoods"], E.Light),
        new("explorer-spice-shop", "Bir baharatçıdan yeni bir tat",
            "Bir baharatçı ya da aktarda daha önce kullanmadığın bir baharatı seç, satıcıdan nasıl kullanıldığını öğren.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Explorer, LifeCategory.Learning,
            30, 60, CostBand.Low, Daytime, true, false, 14, 0, ["local-markets", "cooking"], E.Light),
        new("explorer-viewpoint", "Şehri yukarıdan gör",
            "Güvenli ve herkese açık bir seyir terasına ya da tepeye çık, şehri gün ışığında izle.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Explorer, LifeCategory.Creativity,
            60, 120, CostBand.Free, Daytime, true, true, 21, 0.05, ["nature", "photography"], E.Moderate),
        new("explorer-nature-day", "Şehir yakınında bir doğa rotası",
            "Şehrin yakınındaki işaretli ve popüler bir doğa rotasında gün geçir. Hava durumunu kontrol et, yanına su al.",
            QuestType.Adventure, Difficulty.Medium, LifeCategory.Explorer, LifeCategory.Fitness,
            180, 360, CostBand.Low, Morning, true, true, 30, 0.15, ["nature", "walking"], E.Moderate),
        new("explorer-day-trip", "Yakın bir kasabaya günübirlik gezi",
            "Şehrinden toplu taşımayla ulaşılabilen bir kasabaya günübirlik git; tarihi merkezini ve yerel pazarını gez.",
            QuestType.Adventure, Difficulty.Medium, LifeCategory.Explorer, LifeCategory.Culture,
            300, 480, CostBand.Medium, Daytime, true, false, 45, 0.1, ["neighborhoods", "history", "local-markets"], E.Moderate),

        // ── Kültür (Culture) · 17 ─────────────────────────────────────────────
        new("culture-new-artist", "Yeni bir sanatçının üç eserini keşfet",
            "Adını ilk kez duyduğun bir sanatçının üç eserine (resim, şarkı ya da film) göz at.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Learning,
            10, 20, CostBand.Free, DayPart.Any, false, false, 2, 0, ["art", "live-music"], E.None, Starter: true),
        new("culture-poetry", "Hiç okumadığın bir şairden üç şiir",
            "Adını duyduğun ama okumadığın bir şairden üç şiir oku ve en sevdiğin dizeyi not et.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Learning,
            10, 20, CostBand.Free, DayPart.Any, false, false, 3, 0, ["reading"], E.None),
        new("culture-local-history", "Semtinin tarihini öğren",
            "Yaşadığın semtin adının nereden geldiğini ve bir tarihi olayını araştır, bir yakınınla paylaş.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Explorer,
            15, 30, CostBand.Free, DayPart.Any, false, false, 14, 0, ["history", "neighborhoods"], E.None),
        new("culture-world-music", "Farklı bir ülkenin müziğini keşfet",
            "Hiç dinlemediğin bir ülkenin geleneksel müziğinden bir albüm dinle ve hikâyesini oku.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Learning,
            20, 30, CostBand.Free, DayPart.Any, false, false, 5, 0, ["live-music"], E.None),
        new("culture-new-venue", "Yeni bir kültür mekânını keşfet",
            "Şehrinde daha önce gitmediğin bir kültür mekânını (müze, galeri, kültür merkezi) ziyaret et.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Culture, LifeCategory.Explorer,
            60, 120, CostBand.Low, Waking, true, false, 14, 0, ["museums", "art", "history"], E.Light),
        new("culture-photo-exhibition", "Bir fotoğraf sergisini gez",
            "Bir fotoğraf sergisini gez ve seni en çok etkileyen karenin neden etkilediğini not et.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Creativity,
            60, 120, CostBand.Low, Waking, true, false, 14, 0, ["art", "photography"], E.Light),
        new("culture-short-film", "Bir kısa film gösterimine katıl",
            "Bir kısa film gösterimine ya da festival seçkisine katıl.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Culture, null,
            60, 120, CostBand.Low, Evening, true, false, 14, 0, ["cinema"], E.None),
        new("culture-classic-film", "Hiç izlemediğin bir klasik filmi izle",
            "Sinema tarihinden hiç izlemediğin bir klasiği seç ve izle.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Learning,
            90, 150, CostBand.Free, Evening | Night, false, false, 7, 0, ["cinema"], E.None, Starter: true),
        new("culture-theatre", "Bir tiyatro oyununa git",
            "Daha önce izlemediğin bir tiyatro oyununa bilet al ve izle.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Culture, null,
            120, 180, CostBand.Medium, Evening, true, false, 21, 0, ["theatre"], E.None),
        new("culture-live-music", "Yeni bir türde canlı müzik dinle",
            "Normalde dinlemediğin bir türde canlı müzik performansına git.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Culture, LifeCategory.Social,
            90, 180, CostBand.Medium, Evening | Night, true, false, 14, 0, ["live-music"], E.Light),
        new("culture-architecture-story", "Tarihi bir yapının hikâyesini yerinde öğren",
            "Şehrindeki tarihi bir yapıyı ziyaret et ve hikâyesini yerinde öğren.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Culture, LifeCategory.Explorer,
            60, 120, CostBand.Free, Daytime, true, true, 14, 0, ["architecture", "history"], E.Light),
        new("culture-museum-object", "Bir müzede tek bir esere odaklan",
            "Bir müzede tek bir eser seç, önünde on dakika geçir ve onun hikâyesini araştır.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Learning,
            45, 90, CostBand.Low, Daytime, true, false, 14, 0, ["museums", "art"], E.Light),
        new("culture-documentary", "Bir kültür belgeseli izle",
            "Sanat, tarih ya da mimari üzerine hiç izlemediğin bir belgesel seç ve izle.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Culture, LifeCategory.Learning,
            60, 120, CostBand.Free, Evening | Night, false, false, 7, 0, ["history", "cinema"], E.None),
        new("culture-open-air-concert", "Açık hava konseri ya da festival",
            "Gündüz ya da akşamüstü düzenlenen bir açık hava konserine veya kültür festivaline katıl.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Culture, LifeCategory.Social,
            120, 240, CostBand.Medium, Afternoon | Evening, true, true, 21, 0.05, ["live-music"], E.Moderate),
        new("culture-gallery-hop", "İki galeriyi aynı gün gez",
            "Birbirine yakın iki sanat galerisini aynı gün gez ve aralarındaki farkı düşün.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Culture, null,
            90, 180, CostBand.Free, Afternoon, true, false, 21, 0, ["art"], E.Light),
        new("culture-architecture-walk", "Mimari dönemler yürüyüşü",
            "Şehrinde farklı dönemlere ait üç yapıyı ziyaret eden bir rota çiz ve gündüz yürü.",
            QuestType.Adventure, Difficulty.Medium, LifeCategory.Culture, LifeCategory.Explorer,
            150, 240, CostBand.Free, Daytime, true, true, 30, 0.1, ["architecture", "history", "walking"], E.Moderate),
        new("culture-director-series", "Bir yönetmenin filmografisi",
            "Tek bir yönetmenin beş filmini birkaç haftaya yayarak izle ve her biri için kısa notlar al.",
            QuestType.Epic, Difficulty.Medium, LifeCategory.Culture, LifeCategory.Creativity,
            450, 750, CostBand.Free, Evening | Night, false, false, 90, 0, ["cinema", "writing"], E.None),

        // ── Öğrenme (Learning) · 17 ───────────────────────────────────────────
        new("learning-ten-pages", "Yeni bir kitaptan 10 sayfa oku",
            "Başlamadığın bir kitabı aç ve ilk 10 sayfasını oku.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Learning, null,
            15, 20, CostBand.Free, DayPart.Any, false, false, 1, 0, ["reading"], E.None),
        new("learning-podcast-walk", "Yürürken yeni bir konuda podcast dinle",
            "Hiç bilmediğin bir konuda bir podcast bölümü seç ve kısa bir yürüyüşte dinle.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Learning, LifeCategory.Fitness,
            15, 30, CostBand.Free, Waking, false, true, 2, 0, ["podcasts", "walking"], E.Light, Starter: true),
        new("learning-ten-words", "Öğrenmek istediğin dilde 10 kelime",
            "Öğrenmek istediğin dilde 10 yeni kelime öğren ve her biriyle bir cümle kur.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Learning, null,
            10, 15, CostBand.Free, DayPart.Any, false, false, 1, 0, ["languages"], E.None),
        new("learning-explain-concept", "Bir kavramı öğren ve anlat",
            "Merak ettiğin bir bilim kavramını araştır, sonra bir yakınına kendi cümlelerinle anlat.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Learning, LifeCategory.Social,
            10, 20, CostBand.Free, DayPart.Any, false, false, 3, 0, ["science"], E.None),
        new("learning-stargazing", "Gökyüzünde bir takımyıldız bul",
            "Bir yıldız haritası uygulamasıyla evinin balkonundan ya da penceresinden bir takımyıldız bulmaya çalış.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Learning, null,
            15, 30, CostBand.Free, Evening | Night, false, false, 7, 0, ["astronomy"], E.None),
        new("learning-plant-names", "Çevrendeki beş bitkiyi tanı",
            "Bir bitki tanıma uygulamasıyla yürüyüşünde gördüğün beş bitkinin adını öğren.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Learning, LifeCategory.Explorer,
            15, 30, CostBand.Free, Daytime, false, true, 7, 0, ["nature", "science"], E.Light),
        new("learning-mind-map", "Bir konuyu zihin haritasıyla özetle",
            "Son okuduğun bir yazıyı ya da izlediğin bir videoyu tek sayfalık bir zihin haritasına dönüştür.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Learning, null,
            15, 25, CostBand.Free, DayPart.Any, false, false, 5, 0, ["reading", "science"], E.None),
        new("learning-new-recipe", "Hiç yapmadığın bir yemeği pişir",
            "Daha önce hiç yapmadığın bir yemeği tarifinden pişir.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Learning, LifeCategory.Creativity,
            60, 120, CostBand.Low, Evening, false, false, 7, 0.05, ["cooking"], E.Light, Starter: true),
        new("learning-workshop", "Bir atölye ya da açık derse katıl",
            "Merak ettiğin bir konuda atölyeye, söyleşiye ya da açık derse katıl.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Learning, LifeCategory.Social,
            90, 180, CostBand.Medium, Afternoon | Evening, true, false, 21, 0, ["community-events", "science"], E.Light),
        new("learning-science-center", "Bir bilim merkezini ziyaret et",
            "Bir bilim merkezi, planetaryum ya da bilim müzesini ziyaret et.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Learning, LifeCategory.Culture,
            90, 150, CostBand.Low, Daytime, true, false, 30, 0, ["science", "museums", "astronomy"], E.Light),
        new("learning-language-exchange", "Bir dil değişim buluşmasına katıl",
            "Öğrendiğin dilde pratik yapmak için bir dil değişim buluşmasına katıl.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Learning, LifeCategory.Social,
            60, 120, CostBand.Low, Evening, true, false, 14, 0, ["languages", "community-events"], E.Light),
        new("learning-library", "Halk kütüphanesine üye ol",
            "Semtindeki halk kütüphanesine üye ol ve rastgele bir raftan bir kitap ödünç al.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Learning, LifeCategory.Explorer,
            30, 60, CostBand.Free, Daytime, true, false, 60, 0, ["reading"], E.Light),
        new("learning-bread", "İlk ev yapımı ekmeğini yap",
            "Basit bir tarifle ilk ev yapımı ekmeğini yap; hamurun mayalanmasını izle.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Learning, LifeCategory.Creativity,
            120, 240, CostBand.Low, Daytime, false, false, 14, 0.05, ["cooking"], E.Light),
        new("learning-museum-tour", "Bir müzede rehberli tura katıl",
            "Bir müzenin rehberli turuna ya da ücretsiz konuşmasına katıl ve bir soru sor.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Learning, LifeCategory.Culture,
            60, 120, CostBand.Low, Daytime, true, false, 30, 0, ["museums", "history"], E.Light),
        new("learning-first-aid", "Temel ilk yardım eğitimi al",
            "Güvenilir bir kurumun temel ilk yardım eğitimine katıl ya da online modülünü tamamla.",
            QuestType.Adventure, Difficulty.Medium, LifeCategory.Learning, LifeCategory.Social,
            240, 480, CostBand.Medium, Daytime, false, false, 180, 0, ["science", "community-events"], E.Light),
        new("learning-mini-course", "Kısa bir online kursu bitir",
            "Merak ettiğin bir konuda kısa bir online kursu baştan sona tamamla.",
            QuestType.Epic, Difficulty.Hard, LifeCategory.Learning, null,
            300, 900, CostBand.Free, DayPart.Any, false, false, 60, 0, ["science", "languages"], E.None),
        new("learning-history-series", "Bir tarih serisini bitir",
            "Bir tarih podcast ya da video serisinin tüm bölümlerini birkaç haftada tamamla.",
            QuestType.Epic, Difficulty.Easy, LifeCategory.Learning, LifeCategory.Culture,
            300, 600, CostBand.Free, DayPart.Any, false, false, 90, 0, ["history", "podcasts"], E.None),

        // ── Sosyal (Social) · 16 ──────────────────────────────────────────────
        new("social-reconnect", "Uzun zamandır konuşmadığın birine yaz",
            "Uzun süredir konuşmadığın bir arkadaşına nasıl olduğunu soran bir mesaj gönder.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Social, null,
            5, 15, CostBand.Free, Waking, false, false, 3, 0, ["friends"], E.None, Starter: true),
        new("social-thank-you-note", "Birine teşekkür notu yaz",
            "Hayatına dokunmuş birine neden minnettar olduğunu anlatan kısa bir not ya da mesaj yaz.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Social, LifeCategory.Creativity,
            10, 15, CostBand.Free, DayPart.Any, false, false, 7, 0, ["friends", "writing"], E.None),
        new("social-neighbor", "Bir komşunla tanış",
            "Selamlaştığın ama tanışmadığın bir komşunla kısa bir sohbet et.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Social, null,
            5, 15, CostBand.Free, Waking, false, false, 14, 0, ["community-events", "friends"], E.Light),
        new("social-family-story", "Bir aile büyüğünden hikâye dinle",
            "Bir aile büyüğünü ara ya da ziyaret et; ona gençliğinden bir hikâye anlatmasını rica et.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Social, LifeCategory.Culture,
            15, 30, CostBand.Free, Waking, false, false, 7, 0, ["friends", "history"], E.None),
        new("social-board-game-night", "Kutu oyunu akşamı düzenle",
            "Arkadaşlarınla daha önce oynamadığınız bir kutu oyununu deneyin.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Social, null,
            120, 180, CostBand.Low, Evening, false, false, 14, 0, ["board-games", "friends"], E.None, Starter: true),
        new("social-volunteer", "Bir gönüllülük etkinliğine katıl",
            "Güvenilir bir kurumun düzenlediği bir gönüllülük etkinliğine katıl.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Social, null,
            120, 240, CostBand.Free, Daytime, true, false, 21, 0, ["volunteering", "community-events"], E.Moderate),
        new("social-community-meetup", "Yerel bir topluluk buluşmasına katıl",
            "İlgi alanlarından birinde yerel bir topluluk buluşmasına katıl.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Social, null,
            60, 150, CostBand.Low, Evening, true, false, 14, 0, ["community-events"], E.Light),
        new("social-cook-together", "Bir arkadaşınla birlikte yemek yapın",
            "Bir arkadaşınla ikinizin de ilk kez deneyeceği bir tarifi birlikte pişirin.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Social, LifeCategory.Learning,
            90, 180, CostBand.Low, Evening, false, false, 14, 0.05, ["cooking", "friends"], E.Light),
        new("social-picnic", "Arkadaşlarınla piknik",
            "Birkaç arkadaşınla gündüz bir parkta sade bir piknik yapın; herkes bir şey getirsin.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Social, LifeCategory.Explorer,
            120, 180, CostBand.Low, Daytime, true, true, 21, 0.05, ["friends", "nature"], E.Light),
        new("social-quiz-night", "Bir bilgi yarışması akşamı",
            "Arkadaşlarınla bir mekândaki quiz gecesine katılın ya da evde bir bilgi yarışması düzenleyin.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Social, LifeCategory.Learning,
            90, 150, CostBand.Low, Evening, false, false, 21, 0, ["board-games", "friends"], E.None),
        new("social-teach-skill", "Bildiğin bir şeyi birine öğret",
            "İyi bildiğin bir beceriyi (yemek, müzik, yazılım…) bir arkadaşına yarım saatte öğret.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Social, LifeCategory.Learning,
            30, 60, CostBand.Free, DayPart.Any, false, false, 14, 0, ["friends", "community-events"], E.Light),
        new("social-clean-up", "Bir çevre temizliğine katıl",
            "Belediyenin ya da bir derneğin düzenlediği çevre temizliği etkinliğine eldivenlerinle katıl.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Social, LifeCategory.Explorer,
            120, 180, CostBand.Free, Daytime, true, true, 30, 0.05, ["volunteering", "nature"], E.Moderate),
        new("social-book-club", "Bir kitap kulübüne katıl",
            "Yüz yüze ya da çevrim içi bir kitap kulübü oturumuna katıl ve bir görüşünü paylaş.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Social, LifeCategory.Learning,
            60, 120, CostBand.Free, Evening, false, false, 21, 0, ["reading", "community-events"], E.None),
        new("social-dinner-host", "Küçük bir akşam yemeği düzenle",
            "Üç dört kişilik küçük bir akşam yemeği düzenle; menüye herkesin bir önerisini ekle.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Social, LifeCategory.Learning,
            150, 240, CostBand.Medium, Evening, false, false, 30, 0.05, ["cooking", "friends"], E.Light),
        new("social-game-cafe", "Oyun kafesinde yeni bir oyun öğren",
            "Bir oyun kafesine git, personelden yeni başlayanlara uygun bir oyun önerisi al ve öğren.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Social, LifeCategory.Explorer,
            90, 150, CostBand.Low, Afternoon | Evening, true, false, 21, 0, ["board-games"], E.None),
        new("social-mentor", "Bir gönüllü mentorluk programına katıl",
            "Bir sivil toplum kuruluşunun mentorluk ya da gönüllü eğitmenlik programına başvur ve ilk oturumları tamamla.",
            QuestType.Epic, Difficulty.Hard, LifeCategory.Social, LifeCategory.Learning,
            360, 900, CostBand.Free, Waking, true, false, 180, 0, ["volunteering", "community-events"], E.Light),

        // ── Hareket (Fitness) · 16 ────────────────────────────────────────────
        new("fitness-stretch", "10 dakikalık esneme rutini",
            "Kendini zorlamadan 10 dakikalık bir esneme rutini yap.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Fitness, null,
            10, 15, CostBand.Free, DayPart.Any, false, false, 1, 0, ["yoga"], E.Light),
        new("fitness-yoga-home", "Evde 20 dakikalık yoga",
            "Başlangıç seviyesine uygun 20 dakikalık bir yoga videosu seç ve kendini zorlamadan uygula.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Fitness, null,
            20, 25, CostBand.Free, Morning | Evening, false, false, 2, 0, ["yoga"], E.Light, Starter: true),
        new("fitness-breathing", "10 dakikalık nefes egzersizi",
            "Sessiz bir köşe bul ve 10 dakikalık rehberli bir nefes ya da farkındalık egzersizi yap.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Fitness, null,
            10, 15, CostBand.Free, DayPart.Any, false, false, 1, 0, ["meditation"], E.None),
        new("fitness-stairs", "Asansör yerine merdiven",
            "Bugün gün içinde asansör yerine merdiveni kullan ve kaç kat çıktığını say.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Fitness, null,
            5, 15, CostBand.Free, Waking, false, false, 2, 0.05, ["walking"], E.Moderate),
        new("fitness-walking-call", "Bir telefon görüşmesini yürüyerek yap",
            "Bugünkü telefon görüşmelerinden birini otururken değil, yürüyerek yap.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Fitness, LifeCategory.Social,
            15, 30, CostBand.Free, Waking, false, false, 3, 0, ["walking", "friends"], E.Light),
        new("fitness-walk-photo", "45 dakikalık yürüyüşte 5 ilginç kare",
            "45 dakikalık bir yürüyüşe çık ve yol boyunca dikkatini çeken 5 kare yakala.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Fitness, LifeCategory.Creativity,
            45, 60, CostBand.Free, Waking, false, true, 3, 0, ["walking", "photography"], E.Light, Starter: true),
        new("fitness-new-route-run", "Yeni bir rotada hafif tempolu koş",
            "Bildiğin güvenli bir bölgede yeni bir rota seç ve konuşabileceğin tempoda koş.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Fitness, LifeCategory.Explorer,
            30, 60, CostBand.Free, Morning | Evening, false, true, 7, 0.1, ["running"], E.Vigorous),
        new("fitness-yoga-class", "Bir deneme yoga dersine katıl",
            "Başlangıç seviyesine uygun bir deneme yoga dersine katıl.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Fitness, null,
            60, 90, CostBand.Medium, Morning | Evening, true, false, 30, 0, ["yoga"], E.Moderate),
        new("fitness-swim", "Kapalı bir havuzda yüz",
            "Cankurtaranı olan kapalı bir havuzda kendi temponda yüz.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Fitness, null,
            60, 90, CostBand.Medium, Waking, true, false, 14, 0.1, ["swimming"], E.Vigorous),
        new("fitness-nature-walk", "Parkta bir saatlik yürüyüş",
            "Şehirdeki büyük bir parkta ya da korulukta gündüz, bilinen patikalarda bir saat yürü.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Fitness, LifeCategory.Explorer,
            60, 90, CostBand.Free, Daytime, false, true, 7, 0.05, ["walking", "nature"], E.Moderate),
        new("fitness-city-bike", "Şehirde bisikletle bir tur",
            "Bisiklet yolu olan bir güzergâhta, kaskınla gündüz kırk beş dakikalık bir tur at.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Fitness, LifeCategory.Explorer,
            45, 90, CostBand.Low, Daytime, true, true, 14, 0.2, ["cycling"], E.Vigorous),
        new("fitness-dance-class", "Bir dans dersini dene",
            "Salsa, tango, halk dansı… daha önce denemediğin bir dans türünün başlangıç dersine katıl.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Fitness, LifeCategory.Social,
            60, 90, CostBand.Medium, Evening, true, false, 30, 0.1, ["dance"], E.Vigorous),
        new("fitness-pilates", "Bir pilates deneme dersi",
            "Başlangıç seviyesine uygun bir pilates ya da mobilite dersine katıl.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Fitness, null,
            45, 60, CostBand.Medium, Morning | Evening, true, false, 30, 0, ["yoga"], E.Moderate),
        new("fitness-bike-tour", "Bisikletle sahil ya da park rotası",
            "Bisiklet yolu olan bir sahil ya da park rotasını keşfet. Kask tak.",
            QuestType.Adventure, Difficulty.Medium, LifeCategory.Fitness, LifeCategory.Explorer,
            120, 240, CostBand.Low, Daytime, true, true, 30, 0.2, ["cycling", "nature"], E.Vigorous),
        new("fitness-guided-hike", "Rehberli bir doğa yürüyüşüne katıl",
            "Bir doğa yürüyüşü kulübünün başlangıç seviyesindeki rehberli günlük yürüyüşüne katıl.",
            QuestType.Adventure, Difficulty.Medium, LifeCategory.Fitness, LifeCategory.Explorer,
            240, 420, CostBand.Medium, Morning, true, true, 45, 0.2, ["walking", "nature"], E.Vigorous),
        new("fitness-5k", "5 km'ye hazırlan",
            "Başlangıç seviyesi bir planla birkaç haftada 5 km'yi koşarak ya da yürüyüş-koşu karışımıyla tamamla.",
            QuestType.Epic, Difficulty.Hard, LifeCategory.Fitness, null,
            480, 900, CostBand.Free, Morning | Evening, false, true, 120, 0.15, ["running"], E.Vigorous),

        // ── Yaratıcılık (Creativity) · 17 ─────────────────────────────────────
        new("creativity-photo-theme", "Tek temada 5 fotoğraf",
            "Bugün bir tema seç (gölge, kırmızı, yuvarlak…) ve bu temada 5 fotoğraf çek.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Creativity, null,
            15, 20, CostBand.Free, Waking, false, false, 2, 0, ["photography"], E.Light, Starter: true),
        new("creativity-sketch", "15 dakikada bir nesne çiz",
            "Etrafındaki bir nesneyi seç ve 15 dakikada çiz. Güzel olması gerekmiyor.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Creativity, null,
            15, 20, CostBand.Free, DayPart.Any, false, false, 2, 0, ["drawing"], E.None),
        new("creativity-haiku", "Bugünü üç dizelik bir şiirle anlat",
            "Günün bir anını üç kısa dizelik bir şiirle (haiku) anlat.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Creativity, null,
            10, 15, CostBand.Free, DayPart.Any, false, false, 2, 0, ["writing"], E.None),
        new("creativity-playlist", "Bir anı için çalma listesi hazırla",
            "Bir anını ya da bir mevsimi anlatan 10 şarkılık bir çalma listesi oluştur ve adını koy.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Creativity, null,
            20, 30, CostBand.Free, DayPart.Any, false, false, 7, 0, ["music-making", "live-music"], E.None),
        new("creativity-plating", "Bir tabağı sanat eserine dönüştür",
            "Basit bir yemeği özenle tabakla ve farklı açılardan fotoğrafla.",
            QuestType.Daily, Difficulty.Easy, LifeCategory.Creativity, LifeCategory.Learning,
            15, 30, CostBand.Free, Evening, false, false, 7, 0, ["cooking", "photography"], E.None),
        new("creativity-street-photo", "Sokak fotoğrafçılığı turu",
            "Kalabalık ve güvenli bir caddede sokak fotoğrafçılığı turu yap; insanların rızasına saygı göster.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Creativity, LifeCategory.Explorer,
            60, 120, CostBand.Free, Daytime, true, true, 14, 0, ["street-photography", "neighborhoods"], E.Light),
        new("creativity-short-story", "300 kelimelik bir öykü yaz",
            "Bugün gördüğün bir sahneden yola çıkarak 300 kelimelik bir öykü yaz.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Creativity, LifeCategory.Learning,
            60, 120, CostBand.Free, Evening | Night, false, false, 14, 0, ["writing"], E.None, Starter: true),
        new("creativity-craft", "Basit bir el işi projesi",
            "Basit bir el işi projesini (origami, örgü, seramik boyama…) baştan sona tamamla.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Creativity, null,
            90, 180, CostBand.Low, Afternoon | Evening, false, false, 21, 0, ["crafts"], E.None),
        new("creativity-seed-pot", "Bir saksıya tohum ek",
            "Kolay yetişen bir bitkinin (fesleğen, nane) tohumunu bir saksıya ek ve filizlenmesini takip et.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Creativity, LifeCategory.Learning,
            30, 45, CostBand.Low, Daytime, false, false, 30, 0, ["gardening"], E.Light),
        new("creativity-collage", "Eski dergilerden kolaj",
            "Evdeki eski dergi ya da broşürlerden bir tema seçip küçük bir kolaj yap.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Creativity, LifeCategory.Culture,
            45, 90, CostBand.Free, Afternoon | Evening, false, false, 14, 0, ["crafts", "art"], E.None),
        new("creativity-golden-hour", "Altın saatte fotoğraf yürüyüşü",
            "Gün batımından önceki altın saatte kısa bir yürüyüş yap ve ışığın değişimini fotoğrafla.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Creativity, LifeCategory.Fitness,
            45, 60, CostBand.Free, Evening, false, true, 14, 0.05, ["photography", "walking"], E.Light),
        new("creativity-pottery", "Bir seramik atölyesine katıl",
            "Tek seferlik bir seramik ya da çömlek atölyesinde kendi kabını şekillendir.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Creativity, null,
            120, 180, CostBand.Medium, Afternoon | Evening, true, false, 60, 0, ["crafts"], E.Light),
        new("creativity-instrument", "Bir enstrümanın temel notalarını öğren",
            "Ukulele, kalimba ya da ağız mızıkası gibi bir enstrümanda üç temel akor ya da nota öğren.",
            QuestType.Weekly, Difficulty.Medium, LifeCategory.Creativity, LifeCategory.Learning,
            45, 90, CostBand.Low, Afternoon | Evening, false, false, 21, 0, ["music-making"], E.Light),
        new("creativity-upcycle", "Eski bir eşyaya yeni hayat ver",
            "Kullanmadığın bir kavanoz, tişört ya da kutuyu yaratıcı bir şekilde yeniden değerlendir.",
            QuestType.Weekly, Difficulty.Easy, LifeCategory.Creativity, null,
            45, 90, CostBand.Free, Afternoon | Evening, false, false, 21, 0, ["crafts"], E.Light),
        new("creativity-journal-week", "Bir hafta boyunca günlük tut",
            "Yedi gün boyunca her akşam günün en güzel anını birkaç cümleyle yaz.",
            QuestType.Adventure, Difficulty.Easy, LifeCategory.Creativity, null,
            120, 210, CostBand.Free, Evening | Night, false, false, 60, 0, ["writing"], E.None),
        new("creativity-song-cover", "Bir şarkıyı öğren ve kaydet",
            "Sevdiğin bir şarkıyı bir enstrümanla ya da sesinle öğren ve kendin için kaydet.",
            QuestType.Epic, Difficulty.Hard, LifeCategory.Creativity, LifeCategory.Learning,
            300, 900, CostBand.Free, DayPart.Any, false, false, 60, 0, ["music-making", "live-music"], E.None),
        new("creativity-phone-film", "Telefonla kısa film çek",
            "Senaryosunu yazdığın bir dakikalık kısa filmi telefonunla çek ve kurgula.",
            QuestType.Epic, Difficulty.Hard, LifeCategory.Creativity, LifeCategory.Culture,
            300, 600, CostBand.Free, DayPart.Any, false, false, 90, 0, ["cinema", "photography", "writing"], E.Light)
    ];
}
